var Acudits = [
	"Un nen li pregunta al seu pare: — Pare, pare, què és l'eco? — L'eco, fill meu... — rumia el pare — L'eco es l'únic que té collons de contestar-li a la teva mare!",
	"Dos amics parlant: — Fa vint anys que estic casat amb la mateixa dona, i segueixo enamorat com el primer dia. — Que bé, quina sort! — contesta l'altre. — No creguis, és perillós, sobretot si se n'assabenta la meva dona",
	"El meu veí està boig!! — I això? — El molt cabró no para de donar cops a la paret de matinada i no em deixa estudiar. — I tu què fas? — Doncs segueixo practicant amb la bateria.. ",
	"Sergio Ramos parlant amb Mourinho: — Sergio, ¿por qué ries? — Nah pisha! He estafao a los de la gasolinera! He pedido el depósito lleno, he pagao y me he ido sin poner gasolina! ",
	"En un casament: — S'ha fixat amb la núvia? Miri que arriba a ser lletja... — Escolti, que és la meva filla! — Ah! Perdoni, no sabia que vostè era el seu pare. — Serà desgraciat! Sóc la seva mare!",
	"En què s'assembla un ginecòleg a un repartidor de pizzes? En què tots dos poden olorar el material de treball pero no se'l poden menjar",
	"George Bush i Tony Blair estan en un sopar a la Casa Blanca. S'acosta un invitat i pregunta: — Quins plans tenim pel futur? — I Bush contesta: — Matarem 14 milions de moros i 1 dentista. — L'invitat els mira confós, i pregunta: — ¿Un dentista? ... ¿Per què un dentista? — Bush dóna un copet a l'esquena a Blair i li diu: — Què t'he dit? Ningú preguntarà pels moros!",
	"Van un pare i un fill passejant per les Rambles de Barcelona, i com que és molt tard, decideixen agafar un taxi per tornar a casa. Dins el taxi, el nen veu unes prostitutes que van pel carrer, i li demana al seu pare:— Pare, amb el fred que fa, què fan aquestes dones amb tanta poca roba? — Són models – contesta el pare atònit – que fan una desfilada de roba interior. — Qué modelos y que pollas! – contesta el taxista – son putas niño, y cobran para follar! — El pare cabrejat, pensa: vaia fill de puta! Al cap d’una estona, el nen veu una prostituta amb un nen més o menys de la seva edat, i pregunta al seu pare: — Pare, aquestes dones, també tenen fills? — Si fill, – respon el pare— d’on penses que surten els taxistes?",
	"Un comercial arriba a casa després d'un viatge de dues setmanes, i li diu a la dona: —Carinyo, ves-te traient la roba que farem l'amor. Se'n van ràpidament al llit i fan l'amor de forma salvatge, i el llit no para de donar cops a la paret. El veí s'emprenya i els crida donant cops a la paret: — Ja n'hi ha prou! Porteu dues setmanes així!",
	"Això és un home que arriba a una pensió i demana al propietari: —Quant costa una habitació? — I el propietari respon: — Unes 20 euros i les altres, 50 euros. — Quina diferència hi ha entre les habitacions? — I el propietari respon: — 30 euros.",
	"I vostè, com es diu? — Em dic Jara. — Quin nom més bonic no? — A que ji?",
	"Amor meu, diga'm una paraula amb amor! — Amortiguador",
	"Anunci: Eyaculador precoz busca mujer para... bueno, ya nada",
	"A la farmàcia: — Bon dia, una caixa de preservatius siusplau. — Vol una bossa? — No cal, aquest cop no és tan lletja.",
	"Això és un home molt necessitat de sexe, que està sol al desert, i només hi ha un camell a prop. Cada cop que se l'intenta follar, el camell fuig, i l'home està desesperat. Un dia veu una noia despullada que esta molt bona i uns bandits que la persegueixen. L'home, dispara als bandits i salva la noia. — Gràcies! — Diu la noia — M'has salvat la vida, faré tot el que vulguis! — I l'home contesta: — D'acord... em podries aguantar el camell?",
	"Dos avis a una residència de gent gran: — Escolta, tu què prefereixes, el sexe o el Nadal? — Home, el sexe! Nadal ja n'hi ha cada any!",
	"Josep! — crida el jefe de secció; que no sap que està prohibit beure alcohol mentres es treballa? — No es preocupi jefe, si no estava treballant.",
	"Carinyo... en aquests 25 anys de casats mai no m'has comprat res... — Ah, collons! No sabia que tenies una botiga!",
	"El sargent diu als soldats: — Foc a discreció! — I Discreció va morir cremada",
	"Un ciego pregunta a un cojo: ¿Qué tal andas? Y el cojo le contesta: — Pues ya ves.",
	"Fea! — Diu un borratxo a una dona que passa pel carrer. — Borratxo! — Li contesta la senyora. — Sí sí, pero a mi mañana se me pasa!",
	"Què li diu un tanga a un altre? —Què cony ens posem avui?",
	"Papa, papa, tens un pèl a la boca. — I el pare respon — Doncs no sé de què cony és",
	"Carinyo, ahir a la nit mentre dormies m'insultaves. — I la dona contesta — Qui t'ha dit que estava dormint?",
	"Un nen de 3 anys es mira els testicles mentre la seva mare el banya. — Mami, — pregunta — Això és el meu cervell? — Encara no fill.",
	"Hola, és aquí l'acadèmia d'anglès? — If! If! Between! Between!",
	"Per què el boig es va tirar pel precipici? — Perquè estava boig",
	"Doctor, em toco aquí i em fa mal. Em toco aquí, i també. Em toco aquí, i també. Què tinc doctor? — Vostè té el dit trencat",
	"Què li diu un wc a un boxejador? — A fora ets molt valent, però aquí dins et cagues",
	"Ets mes inútil que l'Spiderman en un descampat",
	"Fa més calor que a la comunió de Charmander",
	"Fa més fred que a la comunió de Pingu",
	"D'on ve la llana verge? De les ovelles lletges",
	"Carinyo, estàs refredat? — Do",
	"Perquè les foques miren cap amunt als espectacles? Perquè hi ha els focos.",
	"Què fa una rata a sota un pont? Esperar un rato",
	"S'obre el teló i es veu un bisbe enfilat a una cadira, espantat per un ratolí. Com es diu el medicament? Bisbeporuc (Vics vapor up)",
	"Això és un gra de sorra que xoca amb un camell al desert, i el gra de sorra li diu — I am sorry. — I el camell contesta: — I am camellorry",
	"Què li diu un jaguar a un altre? — Jaguar you?",
	"A veure, lluiset, — pregunta la professora a l'escola: — Com t'imagines l'escola ideal? — Tancada, mestra!",
	"Escolta, la teva àvia és mecànica? — No, per què? — Perquè aquest matí l'he vist a sota un camió",
	"Mama, l'estufa té dents? — No, fill. — Llavors l'avi s'està cremant.",
	"Mami, mami, l'avi no està bo! — Calla fill, i segueix menjant",
	"Mami, mami, no creus que l'avi es mereix un enterrament més digne? — Calla, fill, i tira la cadena",
	"Mami, mami, puc jugar amb l'avi? — Sí, però quan acabis torna'l a deixar dins de la caixa",
	"Doctor! Sóc asmàtic, és greu? — No. És esdrúixola",
	"Mamá, mamá! En el colegio me han pegado una paliza! — Ay, hijo mío! ¿y te has vengado? —¡Hombre! Si no me vengo para aquí, me matan!",
	"Ostia! Joan, quant de temps! Sí que has canviat! — Ja veus, no sóc en Joan.",
	"Entra un lladre a robar a un banc amb un gat petit a la mà, i diu: — ¡Manos arriba, o aprieto el gatillo!",
	"Què li diu una impressora a una altra? — Aquest full és teu, o és impressió meva?",
	"Això és un autobús de guenyos que va per París i el guia diu: si miren a l'esquerra, veuran a la dreta la Torre Eiffel",
	"Una senyora truca a una carniceria i pregunta: — ¿Que té orelles de conill? — Sí, senyora. — I cap de porc? — Doncs també — I la senyora diu: — Déu meu! Vostè és un monstre!",
	"Com es diu ejaculació precoç en xino? Yatá!",
	"Com es diu menstruació en basc? Elhigo mechorrea",
	"Ei! Vas veure l'apagada d'ahir a la nit? — No, a casa meva va marxar la llum",
	"Mama! Mama! Al cole em diuen cap de setmana! — I això per què, Domingo? ",
	"Cuál es la diferencia entre un globo aerostático y una mujer? Que el globo tiende a subir, y la mujer sube a tender",
	"El capità va dir: — Tots al cuarto de màquines! — I Màquines va haver de dormir al passadís.",
	"Seguid avanzando! Y se perdieron, porque Vanzando no sabía el camino",
	"¡Sacad la foto sin flash! Y Flash no salió en la foto",
	"¡Chutad a gol! Y Gol murió de sobredosis",
	"¡Tiraos a la piscina! Y Piscina quedó embarazada",
	"¡Comeos el bocadillo de tortilla! Y Tortilla se quedó sin bocadillo",
	"Mama, mama! Al cole em diuen despistat! — (veu de robot): Ha triat vostè gasolina sense plom 95",
	"Oye, ¿qué llevas en la cesta? — Si lo aciertas, te doy un racimo — Madalenas?!",
	"Telepizza, ¿qué desea? — Madalenas, no te jode",
	"Un español se encuentra un chino y dice: - ¡Hola! - Y el chino dice: — ¡Las 12:30!",
	"Sabies que la meva germana va amb bicicleta des dels 4 anys? — Ostia, doncs ja deu ser molt lluny",
	"Home invisible busca dona transparent per fer coses mai vistes",
	"— Hola? Bon dia! Trucava per dir que avui el meu fill no pot anar a l'escola, perquè esta molt malalt! — Ah d'acord! Amb qui parlo? — Amb el meu pare",
	"¡No cabe duda! — Dijo el taxista. Y Duda se fue caminando.",
	"Per què està trist el llibre de mates? Perquè te mols problemes",
	"Mama! mama! Avui al cole m'he tragat un disco, i no m'ha passat res! I no m'ha passat res! I no m'ha passat res!",
	"Mama! Dona'm pa! — No! que te'l menges!",
	"Mare, mare, quan menjarem pa d'avui? — Demà, fill ",
	"Dos parlant: —Si endevines quantes gallines tinc, et dono les tres",
	"Hi havia una vegada un home tan gandul, tan gandul, que quan es va morir, a la seva làpida posava: aquí continua descansant...",
	"Per què just al centre de Tokio tenen una bandera de Japó gegant? Perquè es un puntazo",
	"Quin és l'animal que té dues potes i sangra? Mig gos",
	"Cariño, dime algo dulce — Tu puta madre en almíbar",
	"Cariño, dime algo guarro! — Yogur de chorizo",
	"Entra un home a la farmàcia: — Hola, tiene un preservativo? — I el farmacèutic respon: — Condón? — Disculpe, Don farmacéutico, tiene un preservativo?",
	"Entra un home a la drogueria: — Hola bon dia, tindria un pot de sabó? — Ultra? — ¡TENDERO, CABRON! UN POTE DE JABÓN!",
	"Entra David el Gnomo a la farmàcia: — ¿Me da condones? — ¿Control? — ¡No! Sin troll, que me la lian",
	"Això que entra un Playmobil a un bar i demana una fanta: — La vol de taronja, o de llimona? — M'és igual, total... me l'acabaré fotent per l'esquena!",
	"Qué haces Pachi ahí to enyesao? — Pues ná! que iba con la moto, cuando vi una casa que ponia SE TRASPASA... y no se traspasa, no!",
	"PER BIÒLEGS/QUÍMICS: Per què els ossos blancs no es dissolen en aigua? Perquè són polars",
	"PER QUÍMICS: Què fa un electró quan es tira un rot? Booooooohr!",
	"PER QUÍMICS: ¿Qué es una lagosta con un triple enlace? Un lagostín",
	"PER QUÍMICS: Què és una casa amb un grup metil, un isopropil, i un etil? Una casa alquilada",
	"Entra un tio a una farmàcia i pregunta: — ¿Tienen pastillas para la envidia? — Sí. — ¡Qué cabrón!",
	"Quina és la diferència entre un basc i un català quan es queden calbs? Que el basc es compra una boina, i el català es ven el raspall",
	"Què li diu un sord a un tonto? — ¿2+2? — ¡Tres! — Por el culo te la hinco! ",
	"¿Qué hace Superman después de ducharse? Se pone superfume",
	"¿Qué hace Superman cuando se quita la ropa? La deja en superchero",
	"Trump a su mujer: Cariño, nos vamos de gira por los países amigos de EEUU. — Vale, cielo, ¿te espero para comer?",
	"- Papá, dime una mentira. — ¡Hijo!",
	"Mama, mama, mama! Al cole em diuen gordinflon! — I a mi què? — A tu, puta!",
	"Tío! Que graciosa es tu novia! — ¿Graciosa? ¿Por qué? — Porque el otro día me contó un chiste y casi me caigo de la cama",
	"¿Podrías decirme si funcionan los intermitentes traseros? — ¡Ahora sí! ¡Ahora no! ¡Ahora sí! ¡Ahora no!",
	"Están dos durmiendo en pareja y se oye un ruido. La mujer, asustada, dice: — Rápido, vístete, debe ser mi marido! — El hombre rápidamente se pone los pantalones, y dice: — Un momento...! ¡Yo soy tu marido!",
	"¿Cuál es el astro de la mujer? El astropajo",
	"¡Papá! ¡Papá! ¡He perdido la virginidad! — Rápido hija, coge un limón y chúpalo! — Y así recuperaré la virginidad? — No, pero se te quitará esta cara de puta viciosa que tienes!",
	"Van dos putas en moto y se cae tu madre",
	"Van dos amb moto i cau el del mig per la finestra",
	"Saps l'acudit del iogurt? — No. — És clar, és natural.",
	"Saps l'acudit del zoo? — No. — Lògic.",
	"¿Sabes el chiste del hombre entre las dos vallas? — No. — Vaya, hombre, vaya.",
	"Mama! mama! M'he trobat un home que m'ha dit que si li llepava el penis em donava aquesta bossa de caramels!",
	"S'obre el teló i es surt la Megan Fox. Es corre el teló",
	"S'obre el teló i es veu un gitano. Desapareix el teló.",
	"¿Qué animal tiene las cinco vocales y vuela? — Eso los sabe todo el mundo... ¡El murciélagoo! — ¡Pues no! El AEIOU volador",
	"Ei! Saps que Europa atropellen una persona cada 3 minuts? — Joder! Com deu estar el pobre!",
	"Què són 20 negres en una paret blanca? Un codi de barres",
	"Quin és el colmo d'un negre? Estar a la neu i ser un blanc perfecte",
	"Si tires des d'un edifici 3 persones, qui arriba abans a terra? Una dona intel·ligent, un negre o un home blanc? — No ho sé. — Un home blanc, perquè una dona intel·ligent no existeix, i el negre baixa fregant les finestres.",
	"Per què els negres caguen davant de casa seva? Per presumir de què aquell dia han dinat",
	"Va un barco en un muelle y rebota",
	"¡Camarero! Este filete tiene muchos nervios! — Normal señora, es la primera vez que se lo van a comer",
	"Què són 8 boca bits? Un boca byte",
	"Mama, mama! El papa ha vomitat! — Agafa ràpid una forquilla, que sinó després la teva germana es queda amb els millors trossos!",
	"En què s'assemblen un tomàquet i una patata? En què tots dos són vermells menys la patata.",
	"Això és un que li pregunta al seu amic: — En què s'assemblen una bufanda, un sofà i la família? — Mmmmmm no ho sé. — Va, et donaré una pista: la bufanda i el sofà en res. — L'amic es queda confòs, i diu: — I la família? — La familia bé, gràcies!",
	"Doctor, doctor, vinc a que em faci un reconeixement. — Mmmm doncs ara mateix no hi caic.",
	"Com mantenir un tonto ocupat? (llegir a baix)                                                                                                          Com mantenir un tonto ocupat (llegeix a dalt)",
	"Esto que estaba caperucita roja en el bosque, y cae la noche. Y caperucita murió aplastada",
	"El metge li diu al pacient: — Bé, sembla que la seva tos va millorant. — Sí, la veritat és que he estat tota la nit practicant.",
	"Jesús hacia Yoga, y Poncio Pilates",
	"Un amigo dice al otro: — ¿Qué tal la luna de miel? — Y el otro contesta: — ¡Genial! Dos días más y me la tiro.",
	"¡Ei Pachi! ¿Te das cuenta que estamos discutiendo, pudiendo arreglar esto a hostias?",
	"Doctor! Vull que trobi un remei perquè el meu home sigui com un toro, i torni a tenir aquella energia amb la que m'estimava i em feia l'amor. — Molt bé, despulli's. Començarem per les banyes",
	"Això és un pare esta dormint al sofà. Entra la filla petita: — Papa! Papa! Papa! Papa! Papa! Estàs dormint? — No filla, m'estava mirant les parpelles per dintre.",
	"Ahir a la nit em vaig tirar una tia que estava boníssima! Tenia un cul, unes tetes, unes cames.... — I de cara? — Caríssima!",
	"Un gallec arriba a una casa de senyores, i pregunta: — Quan val un servei? — Home, això depèn del temps. — Bé, doncs suposem que plou.",
	"Hi havia una vegada una dona tan gorda, tan gorda, que quan queia del llit, queia pels dos costats.",
	"Entra un home a un bar: — Em posa una ampolla d'aigua si us plau? — ¿Lanjarón? ¿Que agranda y endurece el corazon? — Bueno, millor posi'm una Bezoya.",
	"Saps la diferència entre un polvo de 5 minuts, i una mamada de 5 minuts? — No. — Tens 10 minuts?",
	"Almirall, s'acosten 15 caravel·les per estribor. — Una flota? — No, floten totes!",
	"Oye, ¿tú rezas antes de comer? —No, mi madre es buena cocinera.",
	"Quin és el temps verbal de No hauria d'haver passat? Preservatiu imperfecte.",
	"¡Mamá! ¡Me voy de caza! — Pero hijo! ¿Tienes escopeta? — No mama, ¡me moy para ziempre!",
	"Em podria dir el seu nom de pila siusplau? — Energizer",
	"Dos turistes en un poble. — Escolti, em podria indicar la sortida del poble? —Sí, és aquella gorda d'allà.",
	"Una pareja haciendo el 69 y de repente dice el chico... ¡Anda!, el arzobispo de Toledo se ha muerto! Joder Pepe!!! ¿A qué viene ahora esa chorrada! — Tú y tu puta manía de limpiarte el culo con el periódico.",
	"Oiga, usted que opina de la política europea y la postura Serbo—Bosnia? — No sé... A mí lo que me gusta es que me la chupen",
	"Dos amics estan parlant: — Doncs sí, ara a la meva dona li ha agafat per parlar despres de fer l'amor. La teva fa el mateix?. — Sí, sempre em truca des de l'hotel.",
	"Dos amics que estan parlant: — Entre tu i jo, la meva dona fa molt de soroll quan fem l'amor. — La meva també, sempre la sento des del bar.",
	"Un home molt tímid entra a un bar. — Hola... em.. em pot posar un cafè? — Sol? — Bueno, posi'm—en dos...!",
	"Aixo és un home que entra en un cafè i XOF!!!",
	"Això que un home entra a un bar de pinchos i ai! au! ai! oh! ouch! aich! au!",
	"Això és un pavo que entra en un bar i fa brbrbbrubrubrubrulup!",
	"Doctor! Doctor! Tinc un problema d'inseguretat. Bueno, o no.",
	"Mare, mare! Ha arribat el repartidor de llet! Tens diners o he de sortir a jugar al carrer?",
	"Per què la gent de Lepe guarda una ampolla buida a la nevera? Pels convidats que no tenen set.",
	"Per què els de Lepe posen una tortuga a sobre la tele? Per veure les notícies a camara lenta",
	"Com es pot saber si un fax ha estat enviat per algú de Lepe? Pels segells",
	"Un espermatozoide li diu a un altre: — Escolta, que saps si falta gaire per l'ovari? — Oi tant, encara anem per la gola.",
	"Un grup de nens jugant al pati. — Què? Juguem a funcionaris? — Ah, bé. — D'acord, el primer que es mogui perd.",
	"A una botiga d'electrodomèstics sona el telefon. — Bon dia, truco pel microones... — Doncs se't sent de puta mare!",
	"Doncs al meu fill li han posat ulleres. — Ostia, quin nom més lleig!",
	"Per què els xinos dormen a terra? Perquè el cinquè manament diu No matalàs!",
	"Un home va pel carrer i veu una dona i li diu: — Gorda! — I la dona contesta: ¡Como una tapia, hijo, como una tapia!",
	"Doctor! Doctor! Que vaig de part! — De part de qui?",
	"Quin és el colmo d'un nen orfe? Entrar a una pizzeria i demanar 2 familiars.",
	"Mama, al cole em diuen Mourinho. — Per què fill? — Això els hi pregunto jo, por qué? PUOOR QUE?",
	"Van quatre dones en cotxe. Qui condueix? El de la grúa",
	"Van la Pantoja i en Julián Muñoz en un cotxe. Qui condueix? La policia.",
	"Aixo són dos amics parlant: — No sé que passa, m'agraden totes les dones menys la meva. — A mí em passa el mateix, m'agraden totes menys la teva.",
	"Hola, com et dius? — Joan, i tu? — No, jo no. ",
	"Hola, vostè es diu Joan? — No, però tinc una bicicleta.",
	"Un home es tira d'un edifici i cau de cul a sobre una destral. T'ha fet gracia? — No. — Doncs l'home es va partir el cul.",
	"Com es diu veterinari de gossos en anglès? Dog-tor.",
	"Mama! Els macarrons estan boníssims! — ¿Que vols repetir? — Mama! Els macarrons estan boníssims!",
	"Van dos cargols i xoquen. A l'hospital el doctor pregunta: — Com ha sigut? — No ho sé, tot ha anat molt ràpid.",
	"Entra un home a una botiga de roba. — Bon dia, tenen pantalons de camuflatge? — Sí, però mai els trobem.",
	"Què li diu un boli a un altre? Res, els bolis no parlen.",
	"Què és una llimona amb una capa? Una super-limona. Que es un tomàquet amb una capa? — Un super tomàquet? — Pues no! Un tomàquet imitant la super-limona",
	"Són dos tomàquets dins la nevera, i una li diu a l'altra: — Collons quin fred que fa aquí dins! — I l'altre contesta: — Ostia! Un tomàquet que parla!",
	"Entra un home a una sabateria. — Hola, bon dia, tenen sabates del 42? — No, d'abans de la guerra no en tenim.",
	"Doctor, fa una setmana que no menjo, que no bec i que no dormo. Què tinc, doctor? — Doncs gana, set i son.",
	"Es troben en Joan i en Pere, dos amics. En Pere, diu amb veu molt baixa... — M'he comprat una mini cadena... — I en Joan contesta: — Perquè parles tant baix? — És que m'apreta una miqueta.",
	"Van dos bascos pel carrer, i de cop i volta veuen un cartell que posa: ACEROS INOXIDABLES, i un li diu a l'altre: — ¿Qué? ¿Nos hacemos?",
	"Això son dues vaques, i una li diu a l'altre: — Què en penses d'això de la malaltia de les vaques boges? — No ho sé, a mi no m'afecta, jo sóc un helicòpter.",
	"Va un home i li pregunta a un altre: — Com es diu aquella muntanya? — Quina? — I aquella altra?",
	"Això és un noi que es va a confessar. — Pare, es pecat follar-e una dona negra, de nit, en un túnel? — No fill meu, aixo el que és.... és punteria!",
	"— Ring—Ring. — Digui? — És el 9—3—6—2—3—2—2—0—0? — Sí, sí, no, sí, no, no, sí, no, sí.",
	"Capità! Capità! Terra a la vista! — Calla, burro, que encara no hem llevat ancores.",
	"Quin es el colmo de l'Aladín? Tenir mal geni",
	"Un home li diu a la seva dona: — Si aprenguessis a cuinar, podríem fer fora la cuinera. — I la dona li contesta: — Doncs si tu aprenguessis a follar, podríem fer fora el jardiner.",
	"Era un jugador tant dolent, tant dolent, que una vegada va fer un gol i a la repetició va fallar.",
	"Era una dona tan gorda, tan gorda, que a la nalga esquerra era una hora menys que a la de la dreta.",
	"Doctor! Em fa mal la cama dreta. — Això és cosa de l'edat. — No pot ser! L'esquerra té la mateixa edat i no em fa mal.",
	"Com es mata un elefant blau? -Fàcil, amb l'escopeta de matar elefants blaus.",
	"Hi havia una vegada un home amb tanta mala sort, que va seure a un paller i es va clavar l'agulla.",
	"Hi havia una vegada un tio tan tacanyo, que estava somiant que es prenia un cafè, i es va despertar per no haver-lo de pagar.",
	"L'altre dia vaig veure la teva novia, pero ella no em va veure. — Sí, ja m'ho va dir.",
	"Què beuen els esquimals per emborratxar-se? Licor del Polo.",
	"Què li diu una pedra a una altra? — Quina vida mes dura...",
	"Quin es l'animal mes ferotge? L'elpinten. — Com? — Perquè el lleó no és tan ferotge com elpinten.",
	"Què és un monyo? — Un animal que menja platanys.",
	"Entra un calb a una perruqueria i diu: Ui, perdó!",
	"Què fan els de l'Espanyol quan guanyen la lliga, la champions i la copa? Apaguen la consola.",
	"I tu, com et dius? — Jo, Bienvenido. — Ostres, com la meva alfombra!",
	"Va Sergio Ramos al bosc a buscar un arbre de Nadal. Quan porta dues hores buscant, es diu a ell mateix: — El pròxim arbre que trobi, porti llumetes o no, me'l quedo.",
	"Això és un que li diu a un altre: — I tu, com ho fas per viure tants anys? — Doncs no discuteixo amb ningú. — Home! No serà per això! — D'acord, doncs no serà per això.",
	"Això és un que cau dins un pou. El que va amb ell crida — T'has fet mal? — Encara nooooooooooooooooooooooooooooo!",
	"Dos amics es troben pel carrer: —Què fas, Miquel! +Doncs de puta mare! He fet unes oposicions i ara sóc funcionari! —Que bé! I així ara a les tardes no treballes no? +Què cony, això als matins. A les tardes ja ni hi vaig.",
	"Com es diu un insecte gros que te dues serres? Un bixerrac",
	"Mama! Mama! Al cole em diuen detergent en pols! — No et preocupis Ariel.",
	"Com es diu Fregar els plats en masculi? Fer la migdiada.",
	"Aixó és un electricista que va a fer el manteniment a un hospital. Arriba a una sala amb tot de pacients connectats a diversos aparells i els hi diu: — Senyors, respirin profundament que vaig a canviar un fusible.",
	"Bon dia, el meu nom es Merlí. — Ah! Encantat!",
	"Què és petit, pelut i perillós? Un pollet amb metralleta.",
	"Era un acudit tan dolent, tan dolent, que abusava dels altres acudits.",
	"Era una dona tan lletja, tan lletja, que va enviar una foto per e-mail i la va detectar l'antivirus.",
	"En què s'assembla un metge i les aduanes? Que els dos et treuen el tabac, la beguda i les drogues.",
	"Doncs jo quan prenc cafè no puc dormir. — Doncs a mi em passa al revés! Quan dormo no puc prendre cafè!",
	"Era un home tan alt, que ensopegava un dilluns i arribava a terra el dimecres",
	"Quin és el colmo d'un guardia urbà? Tenir mala circulació",
	"Doctor! Doctor! Que me quemé! — Que te que té?",
	"Què fa un nen de l'Afganistan en un gronxador? Posar dels nervis al franctirador.",
	"I des de quan vostè té l'obsessió que és un gos? — Doncs des que era un cadell, doctor.",
	"—HIJO: Mamá, qué es un aborto? —MADRE: Preguntale a tu hermano. —HIJO: ¿Qué hermano? —MADRE: Exacto...",
	"Això és una parella d'andalusos, i el noi diu: — Corason! — I la noia contesta: — Las 11:30.",
	"Entra un tio a un forn de pa: — Panader! Panader! Tens pa d'ahir? —Doncs si... — Doncs fote't! Haver-ne fet menys!",
	"Maria! Hay una corrida en la tele! — Que quieres, que la grabe? — No! Que la limpies!",
	"Què té un xino entre les cames? Un tira—xines.",
	"Això és un killo que arriba a casa i diu: — Mama, mama, en el cole me llaman macarra. — Vale, hijo, déjate de tonterías y cómete los espaguetis! — I ell contesta: — ¡A QUE ME LOS ENROLLO EN LA POLLA Y TE LOS COMES TU!",
	"Això és un fill que envia un sms a la seva mare. — Mama! Al cole em diuen garrepa! — I la mare contesta amb un altre sms: — No en facis cas fill. Vota Jordi Hereu, l'alcalde de la gent.",
	"Durant un judici, el jutge pregunta a l'acusat: — I com s'ho va fer per obrir la caixa forta i emportar-se tots els diners en 15 minuts? — Senyor jutge, jo no dono classes gratis.",
	"Van dos soldats i el del mig cau... Doncs no! Perquè estaven soldats",
	"Hi havia un tio tan lleig, tan lleig, que va anar a un concurs de lletjos i el van desqualificar per dopping.",
	"Un amic truca un altre: — Joan! Sóc aquí a Vic, pero no trobo la fàbrica de bolis enlloc!",
	"Aneu amb prudència! I la Prudència sempre mes va anar acompanyada.",
	"No vegis si era lleig Albert Einstein. — Pues anda que su hermano Frank!",
	"¿Cómo se llama el hijo de Harrison Ford? ................. Harrison Five!",
	"Hola caputxeta verda! — Hola llop daltònic!",
	"Va un centpeus al bosc, i ensopega, ensopega, ensopega, ensopega...",
	"Quin és el disc mes heavy de tots? El disc dur",
	"Endevina: Té ulls i no hi veu, té bec i no piula, té ales i no vola... Què és? ...........Un ocell mort",
	"Què fa un tonto xafant un rellotge? Matar el temps.",
	"-Hola, ¿está Felix? -No, estoy trixte.",
	"Doncs l'altre dia li vaig comprar un collaret a la meva dona. — Apa, doncs jo la meva la porto deslligada",
	"Escolti, vostè com es diu? — Jo, Joan, però quan estornudo em diuen Jesús.",
	"Mama, mama, a l'escola em diuen Twitter! — I tu què fas? — Res, li dóno a Unfollow",
	"Mama, mama, al cole em diuen friki! — I tu què fas? — Res, em baixa 3 punts el carisma",
	"Hola, és el servei secret? — Ho sento, no ho puc dir.",
	"Com està el teu fill petit? — Bé, ja fa 3 mesos que camina. — Collons, doncs ja deu ser molt lluny!",
	"Arriba un paio a la finestreta del banc. — Hola, com es diu vostè? — Ju—ju—ju—juan Ló—ló—ló—lópez. —Què? És tartamut? — No, el tartamut era el meu pare, i el del registre civil un fill de puta.",
	"Arriba Cèsar al Palau. — On és la meva Cleopatra? — Està al llit amb amigdalitis. — Merda! Putos grecs!",
	"Pare, vinc a confessar-me: M'he ficat al llit amb el cura del poble del costat. — Resa set parenostres i tres avemaries, i la pròxima vegada recorda que la teva parròquia és aquesta i no la del poble del costat.",
	"Puagh! Quina pudor de mort! Oi Joan? Joan? Joaaaan...?",
	"Doctor! Doctor! Venim perquè la meva dona te tres pits. — I vol que n'hi extirpi un? — No, vull que m'implanti un altra mà",
	"Hi ha 10 tipus de persones: les que saben binari i les que no.",
	"Hi ha 3 tipus de persones: les que saben comptar i les que no.",
	"Els 4 evangelistes eren 3: Sant Mateu i Sant Marc",
	"Saps com es deixa un tonto intrigat? — Com? — Demà t'ho explico.",
	"Es troben dos catalans, i un d'ells està fregant dues monedes d'euro. — Què fas Jordi? — Doncs ja veus, aquí, gastant uns eurets.",
	"Mama! Mama! Què és un orgasme? — No ho sé carinyo, pregunta—ho al pare.",
	"Entra un home a un restaurant i el cambrer li pregunta: — Què desitja el senyor? — Una truita. — Francesa o espanyola? — M'és igual, no hi penso parlar.",
	"Qqqqqquiiiiiiinnnnn tttteeeeecccclllllaaaaaattttt mmmmmméééééééééésssssss ssssssseeeeeennnnnnnssssssiiiiiiibbblllllllleeeeeeee",
	"En un manicomi, una infermera veu a un pacient escribint. — Hola Joan, què fas? — Escric una carta — I a qui li enviaràs? — A mí mateix — I què hi expliques? — No ho sé, encara no l'he rebut.",
	"Què és un terapeuta? 1000 gigapeutes",
	"He perdut el meu gos! — Doncs posa un anunci al diari — No siguis tonto, no veus que no sap llegir?",
	"Un home truca la porta d'un endeví. Toc toc! — Qui és? — Vaia merda d'endeví!",
	"Quin animal té entre 3 i 4 ulls?                                   El pi—ojo",
	"Era un nen tan lleig, tan lleig, que la seva mare, enlloc de donar-li el pit, li donava l'esquena.",
	"Es creuen dos ratpenats, i un porta els morros plens de sang. —Ei! Com ho has fet per aconseguir tanta sang? — Veus aquella paret d'alla? — Sí — Doncs jo no l'he vist",
	"Entra un home en un bar. — Una cerveza, por favor! — De presión? —No, alcoholismo.",
	"Quin animal menja pedres i vola? El come-piedras volador",
	"¿Como murió Pinocho? Se hizo una paja y se prendió fuego.",
	"Quin soroll fan els gossos argentins?           Ehteee.... guau!",
	"Lluís! Et trucava per la talladora de gespa.... — Ostia, doncs s'escolta de puta mare!",
	"Això és un tio que es mor un dilluns, i diu: — Collons, si que comencem la setmana malament.",
	"Doctor, doctor, tinc amnèsia — Des de quan? — Des de quan que?",
	"Pregunta del fiscal: — És cert que vostè el dia dels fets es va cagar en els morts del denunciant, en tota la seva puta família, en la mala puta de sa mare i en el fill de puta de son pare, a l'igual que en tota la cort celestial? — Resposta de l'acusat: — No, és fals... jo estava tranquil·lament treballant a la fundició i li vaig dir: Antoni, no t'has adonat que m'has tirat tot l'acer fos per l'esquena i és una sensació molt desagradable?",
	"¡Tu padre es un proscrito! — ¡Pues el tuyo un tigretón!",
	"Doctor! Em sembla que tinc doble personalitat. — Be, doncs segui aquí, i parlarem els quatre.",
	"Papa, papa! Que es nota quan vas borratxo? — Sí, mira fill, molt fàcil. Veus aquelles dues cadires d'allà? Si anessis borratxo en veuries quatre. — Papa, nomes n'hi ha una!",
	"Te vendo un coche. — ¿Y para qué quiero yo un coche vendado?",
	"Papa! On son els pirineus? — I el pare contesta:  Això pregunta—li a la teva mare, que sempre ho endreça tot pels calaixos.",
	"Estan parlant un anglès i un català. I l'anglès li diu: — Vosaltres els catalans quan parleu sembla que trenqueu nous. — I el català respon: — No ho crec.",
	"Com posaries un arqueòleg en un compromís? Ensenyant—li una compresa i preguntant—li de quin període és.",
	"Això és el l'alcalde d'un poble, i li diu al seu secretari: — Secretari, apunti'm tot el que està pendent per divendres. Li respon el secretari: — Senyor president, divendres s'escriu amb 'v' baixa o 'b' alta? L'alcalde dubta, i li contesta: — mmmm... millor que sigui per dilluns.",
	"— Mare, mare... Les llimones tenen plomes? — No, fill meu, mai n'han tingut. — Hum... Llavors he espremut el canari.",
	"Mama! Mama! El vàter dóna voltes? — No, fill meu.  — Hum... llavors m'he cagat a la rentadora.",
	"Com es diu ejaculació en valencià? Tirant lo Blanc",
	"Van dos per tres camins...",
	"¿Qué hace un leproso tocando la guitarra? CARNE PICADA",
	"Què és una persona olorant un encenedor mentre apreta el botó del gas? Un jueu nostàlgic.",
	"Per què es va suicidar Hitler? Perquè no podia pagar la factura del gas.",
	"Per què Superman no va salvar les torres bessones? Perquè se li va punxar la roda de la cadira de rodes.",
	"Una mare dóna a llum el seu bebé. Quan està recuperada, el doctor li diu: — El seu fill està bé, però li hem hagut de posar oxigen. — Quina pena! Jo li volia posar Francesc!",
	"Com es pot fer riure una rossa el dissabte? Explicant—li un acudit el dimecres.",
	"En què s'assembla un arbre i una via de tren? En que cap dels dos beu gazpacho",
	"Van dues mosques en moto. La del mig es crema amb el cendrer, i l'altra xoca amb el sostre i surt per la finestra.",
	"Dues nenes de 6 anys parlant: — M'ha sortit un pel al cony. — I no et molesta per follar?",
	"Arriba una nena de 6 anys a casa, i li pregunta a la seva mare: — Mami! Per què tots els nens tenen la pichulina igual? — De petiteta? — No, de salada!",
	"Van dos pel carrer, i un li diu a l'altre: — Mira aquella tia que bona que està! — Però si té 12 anys! — Però a que n'aparenta 8?",
	"Ahir vaig follar amb una americana. — I què tal? — Molta calor, me la vaig haver de treure al final.",
	"¡Doctor! ¡Doctor! ¡Soy eyaculador precoz! — ¡Coño! — Aaaaahhhhhhhh!!",
	"El profesor de matemàtiques: — Estic indignat! Mes del 80% de la clase ha suspès l'examen! — Ja,ja,ja! Si ni tant sols som tants!",
	"¿Por qué Maria se cayó del columpio? Porque no tenia brazos.",
	"Per què a l'Àfrica no fan els Simpson? Perquè els fan despres de dinar.",
	"S'obre el teló i es veu una lluita de flams. Com es diu el cantant?                                                   Flan Pelea.",
	"Quin és el colmo d'un carnicer? Tenir un fill xoriço",
	"Quin es el colmo d'un químic? Tenir una filla Sossa, i que la seva dona sigui una Potassa",
	"S'obre el teló i surten ple de presoners. Com es diu el poble?                                 Reus",
	"S'obre el teló i es veuen ple de guixos a terra i gent relliscant. Com es diu el poble?                                  S'han fet un lio de guixos (Sant feliu de Guíxols)",
	"Va un hombre y se muere. Moraleja: no vayas.",
	"S'obre el teló i es veu un nen petit que diu: — L'any que ve fare sisè! — Com es diu l'escriptor?                                Estic fent Quint (Stephen King)",
	"S'obre el teló i es veu un petit suisse donant pel cul a un danone. Com es diu la pel·lícula?                                    Postres gays (Poltergeist)",
	"S'obre el teló i surt un home que ven tortitas. Es tanca el teló. S'obre el teló i surt el mateix paio venent frankfurts. Com es diu la pel·lícula?                              El ex-tortista",
	"S'obre el teló i surt una tia amb les tetes plenes de merda. Com es diu el cantant?                                 Bruts els pits tinc (Bruce Springsteen)",
	"—Papá! ¿A tí te gustaba mucho Doraemon no? +¿Por qué lo dices, Nobita José?",
	"Per què els bussos es tiren d'esquena al mar? Perquè si es tiressin de cara caurien dins la barca.",
	"Saps què passa si poses un ou al microones?                                         Que et pilles l'altre amb la tapa.",
	"Fill, ja tens 12 anys, i crec que ha arribat el moment que parlem de temes sexuals. — D'acord pare, que vols saber?",
	"A la consulta: — Despulli's. — Ai, doctor, és que em fa vergonya. — Tranquil·la, dona. — Està bé, on deixo la roba? — Aquí, al costat de la meva.",
	"Saps que es un monopatin? Un mono agafat pels collons.",
	"Pare, vull veure el doctor House. — Calla, pallús, tu aniràs a la seguretat social, com tota la família.",
	"Com es diu butanero en èlfic?    Él—del—gas",
	"Com es diu cambrer en èlfic?     Él—del—bar",
	"Com es diu mariner en èlfic?		Él—del—mar",
	"Dos sords parlant: — Que vas a pescar? — No, vaig a pescar! — Ah! Em pensava que anaves a pescar!",
	"Doctor! Doctor! Com ha anat l'operació? — Què collons doctor? Sóc Sant Pere!",
	"Pare! Pare! Els nens petits d'on venen? — Mira, fill, els porta la cigonya des de París... — Ah.. i pare...la cigonya, qui se la folla?",
	"Això és una tia bona que entra a l'església, i es comenca a despullar, i insinuar-se amb el mossen. Es treu els sostens, els pantalons i es queda completament en boles davant del mossen. El mossen, es gira d'esquenes, es dirigeix al sant Crist i li pregunta: — Senyor! Què se suposa que hauria de fer jo ara? — I el Crist respon tot esverat: — Treu—me els claus! Treu—me els claaaaaaaaaaus!",
	"Això és un home que entra a un confessionari: — Pare, em vull confessar. Sóc un piròman, i m'agrada cremar-ho tot. — El cura, espantat, s'aixeca, ràpidament es va espolsant, i enmig del fum diu: — Tu el que ets és un fill de puta!",
	"Va un peix i s'ofega",
	"Va un ocell i te vèrtig",
	"Això és una festa, i un home té a la mà una ampolla de licor, una de Larios i una altra de Martini. Quina ampolla té la dona? la de Fairy.",
	"¡Papa! Para de echarme queso fundido por la cara, porfavor! — CÁLLATE, NACHO!",
	"Això era un tio amb tanta mala sort, tanta mala sort, que es va tirar al buit, i estava ple.",
	"Això era un tio tan negatiu, tan negatiu, que enlloc de tornar en sí, tornava en no.",
	"Així doctor què? Soc Piscis? Taure? Aquari? —... No, fill, més aviat Càncer",
	"Dos nens es retroben a l'escola després de les vacances de Nadal. — Hola! Què t'han portat els reis? — Doncs una baldufa i uns mitjons, i a tu? — Ah! Doncs a mi una Playstation 3, una bici, un ordinador, una pilota de futbol, una samarreta del Barça, i una minicadena! — Sí, bueno, pero jo almenys no tinc càncer.",
	"Pare! Pare! Per què poses l'arbre de Nadal al menjador, si estem a ple estiu? — Perquè amb el càncer que tens fill, no arribaràs a Nadal.",
	"Mama! Mama! Què seré de gran? — Res, filla, tens SIDA!.",
	"Què és un conjunt de paraplègics tirant—se des de dalt d'un edifici? El Tetris.",
	"Què fan 10 epilèptics dins d'una cabina de telèfon? La festa de l'espuma",
	"Quina és la part més dura d'un vegetal? La cadira de rodes.",
	"Com pots matar 20 mosques de cop? Picant la boca d'un nen del tercer món",
	"Mama! Mama! Em queda bé el vestit? — Si filla, gairebé et tapa la cadira de rodes!",
	"Un avi va al parc, i veu una nena petita, i li diu: — Hola, petita! Si em fas un petonet, et donaré un caramel! — I la nena contesta: — I si te la xupo, em dones la bossa sencera?",
	"Aquí, qui no corre vola. Firmat: un terrorista.",
	"Dos caníbals parlant: — És molt bona la sopa de la mare. — Sí, però la trobarem a faltar.",
	"Era un nen tan lleig, tan lleig, tan lleig... que quan va néixer, la mare va preferir quedar-se la placenta",
	"Era un nen tan lleig, tan lleig, tan lleig... que quan va néixer, el doctor va dir: — Si vola, es un rat—penat.",
	"Era un nen tan lleig, tan lleig, tan lleig... que quan va néixer, el doctor va dir: — Si d'aquí cinc minuts no plora, és un tumor.",
	"L'humor negre és com les cames: o en tens, o no en tens.",
	"Van dos negres en un camp de mines... i BUM! se convirtió en chocapic!",
	"Quina és la diferència entre un jueu i una pizza? Que la pizza no crida quan la poses al forn.",
	"Què fa més gràcia que un nen mort? Un nen mort vestit de pallasso.",
	"Doctor! Doctor! ¿Voy a perder las piernas? — Mira, yo te las doy en una bolsa, y si eso las pierdes, ya es problema tuyo.",
	"Mama, com és possible que tu siguis blanca, el papa sigui xino, i jo negre? — Fill, dóna gràcies de què no lladris.",
	"Era un nen tan lleig, tan lleig, tan lleig, que quan va néixer, el doctor va pegar la mare",
	"Per què el nen va tirar el seu gelat? — Perquè va ser atropellat per un cotxe.",
	"¿Qué es un leproso en moto, a toda velocidad? Una estrella fugaz",
	"Oiga, ¿usted está empadronado? — (Y contesta con una voz muy ronca): — ¡No! ¡Es mi caracter!",
	"S'obre el teló i es veuen cinc ralles de cocaïna. Com es diu la pel·lícula? ............................................... El sexto sin tiro.",
	"S'obre el teló i es veu la Paca posant els dits a l'endoll i enrampant—se. Com es diu la pel·lícula?               El amperio contra—Paca (El imperio contraataca)",
	"S'obre el teló i surten dos homes mirant-se fixament als ulls. Com es diu la pel·lícula?               Seven",
	"Mama! Em passes les galetes? — Agafa—les tu, fill! — Però, mama, si no tinc braços! — Aaaaaaa! No braços, no galetes!",
	"S'obre el teló i surt una mare entrant a l'habitació del fill mentre s'està masturbant i s'està a punt de correr. Com es diu la pel·lícula?                 Todo sobre mi madre",
	"S'obre el teló i es veuen els personatges de Barrio Sésamo borratxos, i Epi està davant de tot serè. De cop, apareix una mà gegant amb aspecte fantasmagòric. Com es diu la pel·lícula?         Epi sobrio primero, la manaza fantasma.",
	"S'obre el teló i es veu un tetrabrik de Don Simón. Com es diu la pel·lícula?          Es—tinto—básico (Instinto básico)",
	"S'obre el teló i es veu un xino i una arpa. Com es diu el personatge? Alpa chino.",
	"Saps quina és la diferència entre una cortina de bany i paper higiènic? — No. — Llavors has sigut tu, fill de puta!",
	"En què s'assemblen els homes a una escombra? A què sense el pal no serveixen per res.",
	"Que li va passar pel cap a la Lady Di al moment de l'accident? El radiador del cotxe.",
	"Oye Mamá! Lady Di en la radio! — Sí, hija, y en el volante, en la guantera, el parabrisas...",
	"Combata la pobreza y el hambre al mismo tiempo: ¡Cómase un pobre!",
	"A ver Jaimito, si yo digo 'fui rica' es pasado, pero si digo 'soy hermosa', ¿qué es? — Mentira maestra.",
	"Això que era un nen tan lleig, tan lleig, que quan va néixer, el van posar a l'incubadora amb vidres polaritzats.",
	"Esto es un enano que va por la calle, y lo para un policía y le dice : ¡Alto!",
	"Això era un nen tan lleig, tan lleig, que el seu pare portava la foto que venia amb la cartera enlloc de la seva.",
	"Era un tio tan lleig, tan lleig, que el va atropellar un cotxe, i va quedar millor",
	"Un dia una noia em va trucar per telèfon i em va dir: — Vine ara a casa, que no hi ha ningú. — Hi vaig anar, i quan vaig arribar efectivament, no hi havia ningú.",
	"Chico cojo de pierna derecha busca mujer coja de pierna izquierda para dar un paseo.",
	"Això era un home tan lleig, tan lleig, que quan anava al zoo els monos li tiraven cacahuets.",
	"Què és una dona guapa i intel·ligent al mateix temps? MENTIDA",
	"Hi havia una vegada una dona tan baixa, tan baixa, que es posava malalta expressament perquè a l'hospital li donessin l'alta.",
	"Hi havia una vegada un home tan petit, tan petit, que es va tirar des d'un gra de sorra amb para—caigudes",
	"Hi havia una vegada un nen tan lleig, tan lleig, que quan anava de càmping els animals del bosc feien fogueres perquè no s'acostés",
	"Mama! Mama! Al cole em diuen mafiós! — Ja ho sé fill — BANG!! (li dispara) — Sabies massa...",
	"El capità va dir: — Terra a la vista! — I es va quedar cec.",
	"Com seria la dona ideal? Una que després de fer l'amor es convertís en pizza.",
	"Com s'havia de dir la filla de la Lady Di? Mercedes del Pilar",
	"Per què en Superman no pot entrar a la cabina de telèfon per canviar-se de roba? Perquè no entra la cadira de rodes.",
	"Ser ciego no es nada, peor sería ser negro. Firmado: Stevie Wonder",
	"En què s'assembla el pòker al sexe? Que si no tens parella, has de tenir una bona mà.",
	"Hi havia una vegada un tio tan gran, que enlloc de frenillo, tenia ABS",
	"Un nen li pregunta a la seva mare: —Mama, tu m'estimes? +Sí fill, però només com amics",
	"Mama! Mama! De gran vull ser skin head. —Calla, fill! A més de negre, ets subnormal!",
	"Una àvia li pregunta a la seva néta: —Filleta, com es diu aquell alemany que em canvia les coses de lloc? — Alzheimer, iaia, alzheimer.",
	"Mama! A fora hi ha uns extraterrestres! —Què dius, fill? —No sé, diuen que vénen del Planeta de Agostini",
	"Toc toc! —Qui hi ha? —Els testimonis de Jehovà —(S'obre la porta). —Hola, què volen? —(Els homes es queden confosos) —Ehm... disculpi senyor, no sé molt bé que se suposa que hem de fer, no ens passa gaire sovint que algú ens obri la porta.",
	"—¡Mamá! ¡Mamá! ¡Estoy poseído! +Dirás poseso, hijo. —Bueno, pos eso.",
	"Mamá! Qué significa cuando en el ordenador dice 'Formateando disco C:>'??",
	"¡Mamá! El pan está blando! —Pues dile que se calle, hijo.",
	"Hi havia una vegada una dona tan gorda, que per rascar-se el cul necessitava un mapa.",
	"Això són dos andalusos parlant: —Oye kiyo! ¿Cómo se dise 'uno' en inglé? +Uán —¡Anda, como mi primo! ",
	"Un noi de 15 anys arriba a casa. —Papá! Hoy he probado el sexo anal! —Este es mi hijo! Ven aquí, siéntate y me lo explicas: —Ja! Estoy yo para sentarme ahora!",
	"Pues hoy me encontraba tan mal que decidí suicidarme tomándome 1000 aspirinas. —¿Y qué paso? —Nada, que a la segunda ya me encontraba mejor.",
	"Entra un home a un bar: — Hola bon dia, un cafè sol siusplau. — I el cambrer diu: — Tothom fora, siusplau!!!",
	"Us presento la màfia xina: (—.(—.(—.(—.(—.(—(—.—).—).—).—).—).—).—)",
	"Això era un tio tant optimista que una vegada va caure per un pou, i el seu amic li va preguntar —T'has fet mal? —Encara noooooooooooooooooo!!!!!",
	"Mamá, mamá, ¿Por qué empujamos el carro hacia el barranco? — Calla niña que vas a despertar a tu padre.",
	"Un policia li diu a una prostituta: —Què faria la teva mare si et veiés aquí? —Em mataria, aquesta és la seva cantonada!",
	"Mi amor, mataron el cura que nos casó. — Te lo dije... ¡En esta vida todo se paga!",
	"Què és un esquelet dins un armari? Un ciutadà de Lepe del segle XV jugant a fet i amagar.",
	"Quina és la part més sensible d'una dona? Pista: 6 lletres i acaba en —ina.                                                                                    Solució: La retina.",
	"Mamá, mamá en el cole me llaman Walkie Talkie, hhhhht! cambio!",
	"Entra un tio al registre civil: — Hola, em venia a canviar el nom. — D'acord, com es diu vostè? — Joan Merda. — JAJAJA no m'extranya que es vulgui canviar el nom, com es vol dir ara? — Jordi Merda.",
	"Papa! El termòmetre ha baixat. — Gaire? — 15 metres, m'ha caigut per la finestra.",
	"Com et dius? — Em dic Cuétara, i tu? — Doncs jo Maria — Hahaha! Com les galetes!",
	"Si una dona té 500 likes i 200 comentaris en una foto, què li falta? Roba",
	"¡Soldado Gutiérrez! — ¡Diga mi capitán! — ¡No lo vi en las pruebas de camuflaje! — ¡Gracias mi capitán!",
	"Entra un tio en un bar i demana 10 whiskys. Se'ls beu, i després demana 9 whiskys. Se'ls beu, i després demana 8 whiskys. Se'ls beu, i després en demana 7. I així fins a 1. Quan acaba diu: — No ho entenc, quan menys bec, més borratxo estic.",
	"To do is to be — Descartes.		To be is to do — Sartre.	Do be do be do be — Sinatra.",
	"Són dues putes en un ascensor. — Fa olor de semen — diu una. I l'altra contesta: — És que m'he tirat un rot.",
	"Mamá, me duele la cabeza. — ¡Cállate niño y apártate de la diana!",
	"Com es pot saber si un avió és italià? Pels pèls de sota les ales.",
	"Toc — toc! — ¿Quién es? — ¡Venimos de Marte! — ¿De marte de quién?",
	"En la consulta del ginecòleg. — Senyora, li tinc bones notícies. — Senyoreta, siusplau. — Ah! Llavors són males notícies.",
	"Tres noies molt guapes van pel carrer. Això que un tio es queda idiotitzat mirant—les. — ¿Qué miras? ¿Qué coño quieres? — Ah! ¡Puedo elegir?",
	"Mama! Ja tinc 13 anys, compra'm uns sostens! — Noo. — Vaa Mama! Que ja tinc 13 anys! — Que t'he dit que no Joan!!",
	"Què li diu la mama pop al nen pop abans de creuar el carrer? — Dona'm la mà, dona'm la mà, dona'm la mà, dona'm la mà...",
	"—¿Qué desea? — Una hamburguesa. — ¿Para comer aquí? — Aquí no, en la mesa — Me refiero ¿Para llevar? —Si, de aquí a la mesa",
	"Todos mis hijos son de apellido distinto.. Firmado: Carlos Distinto",
	"Una parella acaba de fer l'amor. El noi, molt emocionat, li diu a la noia: — A partir d'ara et diré Eva! — Per què? — Pregunta la noia extranyada — Perquè per mi has sigut la primera! — Oh! Que bonic! Doncs jo et diré Peugeot — Per què? — Pregunta el noi confós — Perquè no sé si ets el 206 o el 207! ",
	"¡Doctor! ¿Me examina los pechos? — Notable alto. ",
	"Això són dos pagesos que es compren 50 porcs. I un li diu a l'altre: — Escolta! On els posarem? — I l'altre contesta: — A casa. — I la olor? — Ja s'hi acostumaran!",
	"Ring! Ring! — Digui? — Hola, sóc el seu metge! — Ah! Hola doctor! — Com han anat els resultats dels anàlisis? — Ehmm.. doncs tinc dues notícies: una bona i una dolenta. — Bé, doncs comenci per la bona. — Veurà: li queden 24 hores de vida. — Collons, aquesta és la bona? I la dolenta? — Que estic intentant localitzar-lo des d'ahir.",
	"¿Cuál es el colmo de Batman? Que lo Robin",
	"Se abre el telón y se ve un pavo rojo, un pavo negro, un pavo amarillo, un pavo rosa y un pavo azul. ¿Cómo se llama la serie? Los pavos rangers",
	"Quin és el formatge preferit de Sherlock Holmes? El emmental",
	"Això és a la platja, i un gra de sorra li diu a un altre: VAYA AMBIENTAZOOOOOOO!",
	"Com es diu panader en èlfic?                               Él—del—pan",
	"Eso que va un tío a comprar, y dice: — Hola, ¿me pone un kilo de sal menuda? — Y eso que la tía le empieza a echar la sal en una bolsa, y resulta que la tía tiene un par de tetas enormes, y mientras va poniendo la sal le van botando. Y el tío le dice: — Oiga, me la está poniendo gorda — No! Se la estoy poniendo menuda! — Y dice: — Sí, ¡menuda me la está poniendo!",
	"Esto es una mujer que está en la parada del autobús intentando subirse, pero se lo impide su estrecha falda. Al ver que no lo conseguía, se sube la falda hasta los muslos dejando a la vista su liguero. Una pareja está en la parada, y la mujer le dice a su marido: — ¿No te parece lasciva, sucia e indecente la forma en la que miran los hombres a esa mujer que sube al autobús? A lo que dice el﻿ hombre con los ojos desorbitados: — ¿Qué autobús?",
	"Pónganse la chaqueta de cuero! Y el pobre Cuero se quedó sin chaqueta.",
	"¡Mamá! ¡Mamá! ¿Los pedos pesan? — No, hijo. — Entonces me he cagado",
	"Mamá! Mamá! En la escuela me dicen mentiroso! — Hijo, hace diez años que ya no vas a la escuela!",
	"Mamá! Mamá! En la escuela me dicen Backstreet Boy! — ¿Quién hijo? — EVERYBODY YEEEEAH!",
	"Papá! En el cole me dicen que soy marica! — Pues pégales, hijo — Ay! No, que están muy monos!",
	"Què fa un negre quan fa caca? S'està clonant.",
	"Què li llances a un negre que s'està ofegant? La família sencera",
	"Per què Hitler odiava els jueus? Perquè no coneixia els negres.",
	"Quan tarda una negra en cagar? 9 mesos.",
	"Quants bebés es necessiten per pintar una paret? Depèn amb la força que els llancis.",
	"Per què en els tres reis mags hi havia un rei negre? Perquè algú havia de carregar els paquets",
	"Per què està malament tirar un camió amb 20 negres a dins per un barranc? Perquè n'hi caben 50.",
	"Què li diu una persona sense cames ni braços a una altra persona sense cames ni braços? ¡Qué pasa tronco!",
	"Què és un negre leprós en un jacuzzi? Un plat de choco krispis",
	"Què s'ha de fer quan s'acaba de fer l'amor amb una noia sense pèl púbic? Tornar-la a posar al bressol.",
	"Mamá! Mamá! Ya no quiero más carne en la sopa! — ¡Cállate niño! Encima de leproso, caprichoso!",
	"Mama! Mama! ¿Por qué estás suspirando? — Calla, niño y sigue chupando",
	"María.. ¿Tú tienes el clítoris pegado al ano? — Y dice: — No — Ah! ¡Entonces te estaba chupando una almorrana!",
	"Per què els de Lepe no entren a la cuina? Per què hi ha un pot que diu SAL!",
	"Per què els de Lepe no tenen cadires a la cuina? Per què hi ha un pot que diu No—cilla",
	"Estan dos a una discoteca, i un li diu a l'altre: — Quina hora és? — Dos quarts de cinc. — Collons que tard! — Ah! Haver-m'ho demanat abans!",
	"Jaimito! Diga'm cinc animals que hi ha a la selva! — Cinc elefants",
	"Van dos autocars, un de gent que pot caminar i l'altre de gent amb cadira de rodes. Quin arriba abans? El de cadira de rodes, perquè no s'han de parar a estirar les cames.",
	"Això és un cinema de calbs, on els peluts no hi poden entrar, i va un pelut i es cola a dins. I això que passa un revisor, que és cec. L'home pelut ensenya el cul per despistar-lo. El revisor, li palpa el cul a l'home i diu: — Ustedes dos, se tendrán que separar.",
	"¿Cuál es el único animal que cambia de sexo durante el coito? Las ladillas",
	"NOTICIA: Gemelo suicida mata a su hermano por equivocación",
	"ANUNCIO: Se buscan kamikazes con experiencia.",
	"Això és un inspector que va a un manicomi per veure si en pot treure algun d'allà dins. N'agafa un i li pregunta: — Tú! Quant fan 6x6? — Febrero. — I l'inspector pensa, vale nen! De puta mare. N'agafa un altre i diu: — Tu! Quant fan 6x6? — I diu: — Mil! — I l'inspector pensa, vaia, un altre... N'agafa un altre i li fa la mateixa pregunta: — 6x6? — I diu: — 36!. — L'inspector es queda sorprès, i li pregunta: — Com has arribat a aquesta conclusió? — I contesta: — Fàcil: he dividit Febrer entre mil.",
	"Això és una granota que està a dalt d'un arbre, i en un moment determinat, agafa i es tira daltabaix, i queda malferida. Hi ha un matrimoni de pardals s'ho està mirant, i el pardal mascle li diu al pardal femella: No creus que li hauríem de dir que és adoptat?",
	"Això és un ex-legionari que va al metge. Quan el doctor l'examina veu que té un tatuatge al pit des de fa 20 anys. I el metge li pregunta: — Escolti, i això amb l'aigua no s'esborra? — I contesta: — No ho sé.",
	"Van dos catalans, un argentí i un canari. Ho pilles? — Doncs no. — Doncs la defensa del Madrid tampoc.",
	"Per què a Iker Casillas li diuen l'internauta quan juga contra el Barça? — Per què s'està tot el partit a la xarxa.",
	"Un hombre entra en una farmacia con un niño de 1 año en brazos y dice: —¿Tienes cremita para el culo del bebé? — Sí claro, ¿se la envuelvo? — No hace falta, si me lo voy a follar aquí mismo",
	"Papá papá, como nací yo? — Verás, todo empezó cuando fui a la farmacia y estaba cerrada...",
	"¡Mira, Mira! ¡Tu pez baila Breakdance! —¡PERO MÉTELO EN LA PECERA, DESGRACIADO!!",
	"Cariño, esta es la vaca con la que follo cuando te duele la cabeza... — Si no fueras tan idiota sabrías que eso no es una vaca, es una oveja.. —.—' — Si no fueras tan idiota sabrías que le estoy hablando a la oveja ;})",
	"¿Te gusta el surf? — No ¿Por qué? — Es que tu novia parece una tabla",
	"Si fueras un coche serías un Ferrari. — Ay, ¿Por elegante y deportiva? — No, porque en la báscula vas de 0 a 100 en 3 segundos.",
	"Mama mama en la escuela me dicen puta barata — Pues empieza a cobrar más hija",
	"¿Bailamos? — Claro, ¿Pero quién saca a mi amiga? — Ahhh, por eso no te preocupes, ¡SEGURIDAAAAD!",
	"Un hombre quiere llegar al aeropuerto. — Taxi! ¿Cuánto sale hasta el aeropuerto? — 25 euros. — ¿Y si llevo a mi esposa? — No cambia. —¿Lo ves?, te dije que no vales nada!",
	"— ¿Has oido el caso de esa mujer que se libro de 100 kilos de grasa inútil en una sola noche? — No, ¿cómo lo hizo? — Se divorció",
	"Estaba la maestra preguntándole a los alumnos que qué iban a ser de grandes y pregunta, — ¿Tú qué vas a ser de grande, Pedro? — Yo voy a ser bombero. — ¿Y tú Álex? — Ingeniero. — ¿Y tú Laurita? — Yo voy a ser mamá — ¿Y tú Pepito? — Yo voy a ayudar a Laurita para que sea mamá",
	"El papá de Jaimito le dice a su hijo: — Mira Jaimito, ya hablé con la cigüeña para que te trajera un hermanito! No me jodas papá. Habiendo tantas mujeres, ¿te follaste a una cigüeña?!",
	"Una pareja se conoce en un bar, después de un par de copas, ella le pregunta: — ¿Qué edad crees que tengo? — Por la mirada, alrededor de 22 años, por tu piel y labios unos 20 y por tu cuerpo 18. — Ella dice: — Madre mía!, tú sí que sabes seducir a una mujer...y ahora dime ¿qué vas hacer? — ...Pues la suma",
	"Novio: Vengo a pedirle la mano de su hija. Padre:Cuanto ganas a la semana? Novio:800 euros. Padre: ayy, eso no alcanza ni para el papel de baño. — Novia:Que te dijo mi papa? Novio: — Que cagas mucho ._.",
	"— Papá, ¿Tú alguna vez te enamoraste de una maestra? —Sí. —¿Y qué pasó? — Pues tu madre se enteró, y te tuvimos que cambiar de escuela.",
	"Que has caigut? — No! Les formigues em volien explicar el seu pla per conquerir el món.",
	"Amor eres un encanto! — Y tu una dulzura mi reina! — Sí, ya sé que soy diabética, no tienes que recordármelo cada puto día",
	"— Disculpe, ¿tiene tarjetas que digan 'Para la única mujer de mi vida' ? — Si, tenemos. — Pues póngame ocho. ",
	"Por primera vez el niño se masturba y le cae la leche en la mano >:/ Él, asombrado va donde está su padre y le pregunta: — Papi esto qué es? El papa le dice:— Eso son tus hijos!!!! El niño le pasa la mano x la boca al papa y le dice: — Bechito pal abueloooo...",
	"¿Has probado la comida Africana? — No. — Pues ellos tampoco...",
	"Doctor, quant de temps de vida em queda? — 10 — 10 què? — 10, 9, 8, 7...",
	"—¿Estación de bomberos? ¡Mi casa se incendia! — ¡Vamos para allá! ¿Cómo llegamos? — Pues de preferencia en el camión ese rojo que tienen.",
	"Señor juez, si amar es un delito, me declaro culpable. — Cállese, que usted está aquí por conducir borracho.",
	"¡Papá me quiero suicidar! —¡Por qué hijo?? — Estando de Safari por África un gorila me VIOLÓ — ¡Ay! Hijo la vida continua ... Papá ¿Qué vida? ¿Qué vida? ... Sin él.",
	"Ojalá mi jardín fuera emo para que se cortara solo",
	"— ¡Doctor! A mi amigo le picó una víbora en el pene, ¿qué hago? — Chupar para sacarle el veneno — Oye, ¿Que dice el Doctor? — Pues....Que te vas a morir!",
	"¡Papá, papá, tengo un lío de faldas! —¡Ese es mi hijo, a ver cuéntame! — ¡No se si ponerme la falda azul o la rosa!",
	"— Oye, amor ¿Qué significa: I'm a bitch? ... — Soy una perra. — Sí, ya se, pero... ¿qué significa?",
	"Una mujer muy enamorada le manda un mensaje SMS cariñoso a su marido amado diciéndole: Mi amor: —Si estas durmiendo mándame tus sueños. —Si estas riendo mándame tu sonrisa. —Si estas llorando mándame tus lagrimas. ————————Te amo! A lo que el hombre le responde... — Mi amor. Estoy cagando. — Quieres que te mande algo?",
	"Jo us declaro marit i muller. Ja poden actualitzar el seu estat al Facebook.",
	"¡Cariño, dime algo con amor! — ¡Amorfa!",
	"Entra un tio a la consulta del metge amb dues mulates agafades del braç. I el metge li diu: — Mulates no!!! Li vaig dir MULETES!!!",
	"Com posaries 1000 jueus a dintre un Seat 600? Al cendrer.",
	"María me voy al bar! — Pues pégame ahora, que luego estoy durmiendo!",
	"¡María, tráeme una manzana! — ¿Te la pelo? — ¡Vale! Pero tráeme una manzana!",
	"¿Cuál es el colmo de un ciego? Llamarse Casimiro, tener una hija que se llame Miranda, Vivir el el barrio Vistalegre, en la calle Buenavista, Trabajar en una empresa de Tu—berías, vivir en un no-ve-no B, participar en Eurovisión y trabajar con el Windows Vista. ",
	"Por favor sea usted discreto: Indique con una leve sonrisa si alguna vez le han dado por culo!",
	"Per què els de Lepe posen cinc teles una a sobre de l'altra? Per veure Tele Cinco",
	"Va un cargol i derrapa",
	"L'enciam no és saludable. Intenta saludar-lo, ja veuràs com no et respon.",
	"S'obre el teló i es veuen dues cadires de fusta que valen 5 euros, i una cadira de ferro que val 20 euros. Com es diu la pel·lícula? La más—cara de hierro ",
	"¡Papá! ¡Me pican los mosquitos! — ¡Pues apaga la luz! — (La apaga y entran dos luciérnagas) — ¡Papá! ¡Ya me están buscando con linternas!",
	"¿Qué le dice un mecánico a su mujer? — ¡Mercedes, Benz y ponte A4 patas, que te voy a echar un Volvo en el Porche y nacerá un Clio, porque en esto del Saxo no hay quien Megane. — A lo que su mujer responde: — ¡Y que Mazda! Eres un Golf—o. Me pongo A2 patas y me das por de Trans, luego te como el Polo, y te pongo mirando a León, y que Seat lo que Seat, pero con Stylo.",
	"S'obre el teló i es veu un noi afeminat vestit de fantasma. Com es diu la pel·lícula? La nenaza fantasma",
	"Un amic de veritat no plora per la teva mort. Un amic de veritat es posa a buscar les boles de drac.",
	"El marido le pregunta a su mujer: — ¿Querida, cuando me muera vas a llorar mucho? — Claro, amor, sabes que lloro por cualquier tontería.",
	"T'agraden els nens? — Ai! M'encanten! — Que bé! Perquè se m'ha trencat el preservatiu",
	"S'obre el teló i es veu una taronja gegant. Com es diu el cantant? El tronjón (Elton John)",
	"Se abre el telón y se ve un cadáver con un cuchillo clavado, y alrededor de él está todo lleno de diarrea. ¿Cómo se llama la película? El asesino anda suelto",
	"Entra un hombre a una tienda y dice: — ¿Tiene pelotas para jugar a tenis? — Sí. — Vale pues le espero mañana a las ocho. ",
	"Què fa un català si es troba una tirita? Es fa un tall per aprofitar-la.",
	"Se abre el telón y se ve un basco cagando, y 40 bascos más ansiosos para que termine. ¿Cómo se llama la película? 'Termina Aitor'",
	"S'obre el teló i es veu un actor entrebancant—se en una escala. Com es diu l'actor? Sin—ver-este Escalón (Silvester Stallone)",
	"S'obre el teló i es veu la tecla enter i els cables de sota el teclat al descobert. Com es diu la pel·lícula? Los IntroCables",
	"Se abre el telón y aparece el número 1 y el número 2 andaluces llamando a una puerta. ¿Nombre de la película? Estár Tre? (Star Trek)",
	"Se abre el telón y no hay nada. ¿Cómo se llama la película? Lo que el viento se llevó",
	"¿En qué parte de África hay más gente? Depende de hacia donde sople el viento.",
	"Se abre el telón y aparece el coche fantástico diciendo: Hola Michael, buenos días, hoy tenemos que ir a detener unos ladrones, llevarlos a comisaría, luego ir a por unos traficantes de droga en el muelle, luego tienes que llevarme al mecánico para hacerme una revisión, y luego tenemos que redactar unos informes... ¿Como se llama la película?										Cállate Kit (Karate Kid) ",
	"S'obre el teló i es veu un extraterrestre anant a peu. Com es diu el poble? 'Sen se-l'ovni' (Sant Celoni)",
	"S'obre el teló i es veu un ordinador amb el Firefox. Com es diu la pel·lícula? Modzilla",
	"S'obre el teló i es veu el mar amb només una tonyina. Com es diu la pel·lícula? Ultim-atun a la Tierra",
	"S'obre el teló i apareix un cec. Es tanca el teló. S'obre el teló i es veu la mateixa persona, però veient—s—hi bé. Com es diu el cantant? Ja—miro guai (Jamiroquai)",
	"S'obre el teló i es veuen 100 pendrives USB venint a Espanya amb patera. Com es diu la pel·lícula? Memòries d'Àfrica",
	"S'obre el teló i surt una noia amb bicicleta. Nom del país? Mossa—amb—bike",
	"S'obre el teló i es veu un home agafant els pits a una dona. Com es diu el cantant? Les tinc (L'Sting)",
	"S'obre el teló i es veu un home repartint droga des de dalt l'escenari. Com es diu el cantant? Tomeu Penya",
	"S'obre el teló i es veu un home engegant una moto i se li para. N'agafa una altra, l'engega i se li para. N'agafa una altra, l'engega i se li para... Com es diu el poble? L'Escala ",
	"S'obre el teló es veu un ós corrent, i un home que l'estira per darrere. Com es diu el pilot? Frenando Al—oso",
	"S'obre el teló i es veu una plaça amb 500 persones que es diuen Josep. Com es diu l'estat d'Amèrica? Massa—Jusseps",
	"A vegades no et passa que et sents comprimit? — Zip. — Què RAR no? ",
	"Per què els de Lepe fan els edificis rodons? Perquè els gossos no es pixin a les cantonades",
	"Per què els de Lepe es masturben davant les bústies? Per què posa 'Correos'",
	"S'obre el teló i es veuen ple de dones. Com es diu el supermercat? Cap—rabo",
	"Això és un home que truca a un porter automàtic i diu: 'No hay nieve en St. Moris' — L'espia viu al cinquè!",
	"Qué le pide el sobrino de Michael Jackson a los reyes magos? Un tio—vivo",
	"Doctor, doctor! Tinc complex de lletja! — De complex, res, filla",
	"Quina és la diferència entre una muller i una amant? 40 quilos",
	"Què li diu una fulla verda a una de morada? — Respira!!",
	"Què us ha ensenyat la mestra avui Jaimito? — Res, avui portava pantalons",
	"Per què les dones tenen la regla? Per què la ignorància es paga amb sang.",
	"Que tenen les dones una vegada al mes, i els hi dura 2 o 3 dies? El sou del marit",
	"Hi havia una vegada un home tan gras, tan gras, tan gras, que s'havia de posar el cinturó amb un boomerang.",
	"Mama, aquesta sabata a quin peu va? — Al dret, despistat! — Gràcies! I aquesta altra?",
	"Mama, mama! Per què el pare corre en zig—zag? — Calla fill i recarrega l'escopeta!",
	"Què és verd, i en prèmer un botó es torna vermell? Una granota en una batedora.",
	"Què diu la duquesa d'Alba quan es treu els sostens? Que fred que està el terra!",
	"Quin és el colmo d'un oculista? Tenir una dona malaguenya.",
	"Maria! Renta els nens! — No cal, els reconec per la veu",
	"Té sabates de cocodril? — Sí, senyor, quin peu calça el seu cocodril?",
	"Bon dia, sóc l'afinador de pianos! — Però si jo no l'he pas trucat! — Ja, però la seva veïna sí!",
	"Entra un esquelet a un bar i diu: — Posi'm un suc de taronja i una fregona.",
	"Per què Iker Casillas no té fred a l'hivern? Per què juga amb 10 mantes",
	"En què s'assemblen els Teletubbies i el Madrid? Que els dos salten a la gespa a fer el tonto.",
	"El meu marit cada dia em troba més interessant — I això? — És que és arqueòleg",
	"¿Por qué los niños negros se asustan cuando tienen diarrea? Porque creen que se estan derritiendo.",
	"De que murio Bob Marley? De un porrazo.",
	"Papá, papá.... Tengo una noticia buena y una mala. ¿Cuál quieres oír primero? — Dime la buena. — A tu coche le funciona perfectamente el airbag.",
	"Si tengo 20 manzanas en una mano y en la otra tengo 15 ¿Qué tengo? — Las manos muy grandes",
	"Hola qué tal Juan, ¿y los niños? — Bien gracias. — y... ¿qué es de Pilar?. — Pues arrancarse los pelos uno a uno.",
	"¿Qué dice una pija cuando ve el mar? — O sea!",
	"— Papá! ¿Cuál es el mejor mes para casarse? — Muy fácil hijo, es Juniciembre. — Papá, este mes no existe. — Ya lo sé hijo, ya lo sé",
	"Com es diu el pare del príncep blau? Blu Rei",
	"— Capità, capità, que el transatlàntic s'enfonsa! — Doncs salvem—nos nosaltres primer! — Però capità, que hi ha dones! — Sí home, estic jo ara per pensar en fotre un polvo!",
	"Dos infants al parvulari: — L'altre dia vaig trobar un condó en un parc. — Ah, si? I què és un parc?",
	"PER BIÒLEGS: Quina és la única proteïna que no paga impostos? L'ATP sintasa",
	"Esto es una família de indios formada por un padre, una madre, dos hijos y una hija. El pequeño le pregunta al padre: —¿Por qué los indios tenemos nombres tan raros? — Mira hijo te pondré un ejemplo, tu hermana se llama Estrella Fugaz porque cuando la estabamos haciendo cayó una del cielo, tu hermano se llama Caballo Veloz porque cuando nació pasó uno a gran velocidad. ¿Lo entiendes Goma Rota?",
	"A ver Jaimito — Pregunta la profesora — Si tienes un euro, y le pides otro a tu padre ¿cuántos euros tienes? — Pues un euro, profesora. — Jaimito, no sabes nada de matemáticas. — Y tu no sabes como es mi padre.",
	"Entra un home a una fruiteria: perdoni, voldria pomes — Fuji?— Si, ara marxo, però posi’m unes pomes",
	"¿Qué es el arte? — Morirse de frío",
	"¿Cómo se llama la madre del topo? Topotamadre",
	"S'obre el teló i apareix un amic de l'Spiderman. Com es diu el medicament? Espidifriend ",
	"Que le dice un jardinero a otro? Disfrutemos mientras podamos",
	"Quieres jugar a que te viole? — No!! — Este es el espíritu!",
	"Se abre el telón y se ve conjunto de niñas en fila, y a la primera le falta una mano. ¿Cómo se llama la ceremonia?    La primera con muñón",
	"Se abre el telón y se ve a Angelina Jolie cavando un agujero con las manos, y a su lado está Brad Pitt con una pala. ¿Cómo se llama el concurso? Pasa pala Brad",
	"Se abre el telón y se ven dos mandos de la Playstation gigantes. ¿Cómo se llama la película? Super Man dos",
	"Dos amics parlant: — Escolta, i tu no penses casar-te, o què? — Jo? No! Si tinc dues germanes que em cuiden, em mimen, i em donen tot el que necessito. — Ja.. però les teves germanes no et poden oferir el que et pot oferir una dona de veritat... — I qui t'ha dit que són germanes meves?",
	"Ala! ¿Desde cuándo hace que tienes trillizos? — No! Si no son trillizos, es que es un niño muy nervioso",
	"Un señor sube a un taxi y dice: — Señor, señor, no corra tanto, es la primera vez que subo en un coche.— El conductor dice: —Estamos de enhorabuena, yo es la primera vez que conduzco!",
	"Cómo murió Peter Pan? De una colleja del capitán garfio.",
	"Oye, ¿bailas? —No. —¿Y eso? —Eso es mi prima, y tampoco baila.",
	"Chuck Norris pot passar documents del Word a PDF amb el buscaminas",
	"Chuck Norris va instalar el windows vista en una torradora... 20 anys abans que nasqués Bill Gates",
	"Tío! El otro día me picó una serpiente! —¿Cobra? —Pues no sé, yo creo que es gratis",
	"—Doctor, últimament no sé què em passa. Em sento grassa, lletja, i penso que no atrec els homes... Què tinc? — Vosté té Raó.",
	"Què és el pitjor que et pot dir la teva dona mentres practiques sexe? —Carinyo, ja sóc a casa!",
	"—Sherlock, ¿qué hace dibujándose una L en la cabeza? —Ele mental, querido Watson",
	"—Voy al Mercadona y me meteré naranjas en el bolso. —¿Podrías? —No coño, de las buenas.",
	"—No podemos con esto, es muy pesado. — Voy a llamar a mi prima de Zaragoza. — ¿Por qué? — Más vale maña que fuerza.",
	"—¿Qué tal la mujer de tu hijo? — Nuera lo que me esperaba",
	"Que hacen mil testículos subidos a un árbol? Una sombra de cojones.",
	"—¡MAMÁ YO QUIERO QUE ME CREZCAN YA LAS TETAS! — Pero si tienes 7 años... —¿Y qué problema hay? — Ninguno, Pablo.",
	"Yo cavo, tú cavas, él cava, nosotros cavamos, vosotros caváis, ellos cavan. No es un poema muy bonito, pero es muy profundo.",
	"—Vecino, ¿qué película te apetece ver hoy? — La que sea vecina. — He dicho película.",
	"Ayer vi a un negro con un teléfono móvil. Por un momento pensé que era el mío. Pero no, el mío estaba en casa fregando el suelo.",
	"Ha llegado a las tiendas un muñeco musulmán que habla. No sabemos qué cojones dice porque nadie tiene huevos a tirar de la cuerda.",
	"— Mamá yo siempre me meto con el yonki de mi instituto. — Hijo no tienes que reirte de nadie. — No me has entendido.",
	"— ¿Tienes un cigarro? —¡Pero hija!,¿tú fumas? — Si no, ¿qué hago después de follar? — ¡¿¡Ya follas!?! —¡Coño, me tendré que pagar las drogas!",
	"— Cariño,donde está mi regalo?..+ Ves ese Ferrari rojo de ahi fuera?...— Wooooww halaaa siiiii! + Te he comprado un pintalabios del mismo color.",
	"— Mamá, esta ternera esta muy dura. — ¿Te la corto? — No, no, ya me callo.",
	"— Le llamo desde el 1004 + Le cuelgo desde el 2018",
	"— Eres un bombón. — ¿Tan dulce soy? — No, es por el sonido 'bom bom' que haces cada vez que andas, gorda.",
	"— ¡Estás cuadrado! — Juan, deja de hablarle al tetrabrik. —JAJAJA Es que es la leche.",
	"— Lo siento, mi vida, mi padre no aprueba nuestra relación. —BEEEEEEEE.",
	"— Soy Aragorn. — Yo soy Valladolird.",
	"— Mamá, ¿me enseñas a coser? — Joder hija, aparte de manca, gilipollas.",
	"— Cariño, si un día muero, quiero que te cases con Antonio. — ¿Con Antonio? Pero si os lleváis fatal. — Pues por eso, que se joda.",
	"— Dime un numero acabado en cinco. — Quince. — Por el culo te la... CABRÓN.",
	"— Watson, aquí hay gato encerrado... — ¡Sherlock, saca a Bigotitos de esa jaula!",
	"— ¿Que tal ha ido la operación de apendicitis, Doctor? — Bien. — ¿Se me verá cicatriz? — Eso depende de lo puta que sea Usted.",
	"— ¿Vas a aprobar el examen de protones y neutrones? — Nu cleo.",
	"— ¿Como te llamas? — Mayo, ¿y tu? — Julio. — JAJAJAJA ¡Tienes nombre de mes!",
	"— ¿Por qué te has puesto 'Fa' en la frente? — Es una nota mental.",
	"Si Rajoy fuera un super héroe sería Despider-Man.",
	"—¿Quiénes hijo? —Mamá, en la escuela dicen que ves el futuro...! Mierda!",
	"—mamá, que haces en frente del ordenador con los ojos cerrados? —nada, que windows me dijo que cerrara las pestañas",
	"—Oye, que significa Do you speak english? —Hablas inglés? —No, por eso pregunto...",
	"A caballo regalado... yonki contento",
	"¿Quien invento el triatlon? Los gitanos, que van a la piscina andando y vuelven en bici.",
	"—Hola buenas, quería comprar un perro... —¿Pekinés? —Pa' mi madre, que le encantan los animales.",
	"Si no sé una contraseña, escribo siempre 'Stephen Hawking'. No sirve de nada, pero aparece 'su contraseña es inválida', y me parto.",
	"Hola mi amor, donde estás? —En casa a punto de dormir, y tu ? —En la discoteca detras tuyo ....",
	"Uno que entra al bar: —Ponme 6 casallas! —Ostia ¿qué celebras? —Mi primera mamada —Enhorabuena, la casa te invita a una séptima —Espero que me quiten el sabor a polla!",
	"—¿Y qué te ha dicho el médico? —Que confundo los colores con los números... —Buah, menudo marrón! —Por el culo te la hinco!!",
	"—En el examen voy a hacerles unas preguntas y la respuesta debe ser oral. Usted, por ejemplo: En qué año se descubrió América? —Oral.",
	"—¿Has visto cómo toca el violín mi hijo? ¿Qué te parece la ejecución? —La ejecución quizás es exagerado, pero un par de hostias sí le daba.",
	"—oye Sócractes, porque el chino del bazar se ha forrado en tan poco tiempo? —Sólo sé que no cerraba",
	"—Juan, tenemos un problema con tu mujer —¿Cuál? —Que nos está engañando a los dos...",
	"—Doctor, se me cae la piel a trozos… —Leprosa. —¿Algún título en concreto?",
	"No entiendo cómo alguien puede perder un tren. Son enormes.",
	"Ei tío, me dejas 1000 euros? —No llevo nada suelto encima... —Y en casa?  —Todos bien, gracias.",
	"Mami mami... de dónde vienen los niñitos? Hijito mio... Papa pone una semillita muy pequeñita en el vientre de mama y se la empuja con la polla",
	"-Mor una noia a Tenerife atropellada per un tren. Els ha informat Matías Prats a les 8.00 h... una menys a Canàries",
	"que le dice un vagabundo a otro? en tu caixa o en la mía",
	"—Antonio, donde vas? —A llevar las gallinas al veterinario que no paran de soltar esputos... —Pues llevate también a tu hermana!! —Que también esputa? —Más que las gallinas!",
	"+Mamá, ¡en el colegio me llaman incoherente! —¿Por qué, hijo? +Toalla.",
	"—Mi hijo se metió a clases de natación. —¿Y qué tal lo hace? —Nada mal.",
	"—perdona, me debías 500€ no? —Estás perdonado.",
	"—Han encontrado a tu mujer y a tu hijo en el estanque. Están los dos muertos —¡¿ESTÁN QUÉ?! —Sí hombre. El sitio ese donde viven los patos.",
	"—A ti que te molesta mas la ignorancia o la indiferencia? —Ni lo sé, ni me importa",
	"—Dime de qué presumes y te diré de qué careces. —De qué presumes. —De qué careces.",
	"-Me río, voy Tajo. +Se dice 'taja'. -Pero no existe el río Taja. +Papá, estás fatal. -Sí. Es que estoy Ebro. +Papá, porfa. -Cállate, Miño.",
	"Si masturbarse es pecado y suicidarse también, matarse a pajas desbloquea algún logro en el infierno?",
	"Mueren 4 personas en Lepe: 2 en los asesinatos, y 2 en la recreación de los hechos.",
	"- Que haces en mitad de la calle moviendo los brazos? -Espantando unicornios! -Pero que dices xalao si aqui no hay! -Pues claro, porque funciona!",
	"—Esa es un travesti.  —¿Cómo lo sabes?  —Se le nota un huevo.",
	"-¿Puedes decirme desde cuando viajas por el tiempo?  -Desde luego.",
	"Juegos olímpicos en Lepe. Discurso de inauguración.  -O... o... o... o... o - Señor alcalde, los aros olímpicos no se leen.",
	"-Perdona, la Notaría? -Si me l'arrima...",
	"-He perdido a toda mi familia en un incendio. -Te entiendo perfectamente. -¿Tambien te pasó? - No, pero hablo castellano.",
	"Señorita, ésto es un control de alcoholemia, coja aire y sople aquí. -Perdone agente...eso es su polla! -Ah, pues no va tan borracha, circule, circule.....",
	"-¿Entera? -No, sólo la puntita. -No, estúpida, la leche. -Ah! en la cara.",
	"Yo ya sabía que Amstrong se dopaba. Es imposible subir a la luna en bici y tocando la trompeta sin ayuda de las drogas.",
	"A mi no me afecta el precio de la gasolina, yo siempre echo 20€",
	"-¿Bomberos? Mi casa está ardiendo! -¿Dónde se originó el fuego? -En la prehistoria, y yo qué cojones sé, pero VENGAN YA!",
	"—Hola ¿Tienes novio? -No. -¿Y eso? - Sí, y también bachiller",
	"—He escrito un libro. -¿Y porqué has dibujado un dedo en la primera página? —Es el índice. -Ah",
	"¡LOS DISLÉXICOS TAMBIÉN SOMOS PERSIANAS!",
	"Hombre: Cariño, por qué nunca me entero cuando tienes un orgasmo? Mujer: Porque nunca estás cuando pasa.",
	"-Tu como sabes cuando tu pareja se va a correr? -Muy facil, cuando se pone el chandal",
	"¿En qué se convierte un café cuando sale de la cárcel? En un expreso.",
	"-Doctor, ¿tiene pastillas para la baja autoestima? -Si, tome. -No, déjelo, no me las merezco",
	"Un hombre va a coger un avión y le informan: -Señor,lamento comunicarle que su avión viene demorado. -No si a mi el color me da igual..",
	"-Papá, ¿qué haces? -Se llama masturbarse, y pronto lo harás tú. -¿Y eso por qué? -Porque se me cansa la mano.",
	"Per què Messi no ha batejat el seu fill? Pq no sigui Cristiano",
	"Mi mujer està gilipollas, me ha dejao una nota en el frigorífico y pone 'me voy de casa porque esto no funciona' y llevo dos horas mirándolo por todos los sitios y esto enfría de puta madre.",
	"El marit li proposa a la seva dona una repte: -diga'm alguna cosa que em faci enfadar i em posi content al mateix temps.- Fàcil,-diu ella -de la teva colla d'amics ets qui la té més gran",
	"El gato de mi novia murió, así que me pidió que le comprase otro igual. No sé qué coño va a hacer con dos gatos muertos.",
	"-Cariño, no sé que poner en la tele, golf o porno. -Pon porno, ya sabes jugar al golf.",
	"- Mamá, me sale sangre del coño... - Tranquila hija, eso será que tienes la regla....  - si, si... la regla, el boli, el compás, los rotring, la flauta...",
	"—¿Tú en qué trabajas? —Soy inventor. La rueda, la penicilina, la radio. Todo mío. —¡Eso es mentira! —Ya ves, me lo he inventado todo.",
	"l'única cosa bona que han inventat els serbis són els Self, aquells restaurants que t'ho agafes tot tu mateix",
	"—Cariño, ¿me quieres? — Не, али желим да ми даш пољубац црно — ¿Qué dices? ¿Estás de broma? — No, te lo digo muy en serbio.",
	"En una entrevista de trabajo: - ¿Cuál dirías que es tu mayor defecto? - La honestidad. - ¿La honestidad? no creo que eso sea un defecto...- Me importa una mierda lo que creas.",
	"Ta mare és tan gorda que va passar per davant de la tele i em vaig perdre tres capítols de La Riera",
	"Eres tan fea que los obreros te ven y se ponen a trabajar.",
	"Eres tan fea... que sólo te guiñan el ojo los francotiradores...",
	"Si pierdo el conocimiento entre abril y junio, ¿mesdemayo?",
	"-Vengo a matricularme en bachiller. - En que rama? - Ya está! ... Como soy negro, el negro al árbol!",
	"CAPRICORNIO Amor: bien. Posibles peleas con los Piscis. PISCIS Amor: bien. Los Capricornio dicen que los Piscis sois unos hijos de puta.",
	"—De l'1 al 10 quin és el teu nivell de sordera? —Sí.",
	"Un negro que entra a una merceria y pregunta: -Tenéis calcetines punto blanco? -Los que tu quieras, puto negro",
	"—Mamá, mamá en el colegio me llaman Mariano Rajoy. — Es que te llamas así. — Ah. ",
	"—Disculpe, ¿sabe usted cuánto tarda en explotar un bebé en el microondas?  — Lo siento, no sé contar mientras me masturbo.",
	"-Es mi hija, la menor.  -Ah, pues este es mi hijo, fa sostenido.",
	"-Hoy hace un año y 8 meses que me llamaste rencoroso.",
	"Mare, tu què volies? filla o fill? —...Doncs... Jo només volia aprovar l'assignatura",
	"Pare, tu què volies? filla o fill? — Jo l'únic que volia era follar",
	"Estoy totalmente en contra bebe Coca-Cola de la publicidad subliminal",
	"He llamado al móvil a Bruce Springsteen, pero me ha salido el Buzon The Boss.",
	"— Dime a que grupo islamista perteneces.  — HAMAS.  — ¡DÍMELO!  — HAMAS.  — ¡QUÉ ME LO DIGAS!  — HAMAS.  — TORTURADLO HASTA QUE CONFIESE.",
	"-Ayer vi dos hombres y medio!  +Y que tal?  -Mucha sangre..",
	"A mi la arquitectura griega me gusta en parte sí y en Partenón.",
	"Vivo con el miedo de que alguien secuestre a mi suegra que vive sola, en la calle Miramar, Edificio Las Rosas, Numero 7, planta 3, segundo D.",
	"—Cari, esto no es lo que parece.  — HIJODEPUTA! ESTAS FOLLANDO CON MI HERMANA!! EN NUESTRA CAMA!!  — Ah, pues sí, entonces sí.",
	"Jodida dixlesia el otro día le quería decir a mi mujer que me pasara la mostaza y le dije: Me estás amargando la vida pedazo de hija de puta",
	"-Papa soy adoptado?  +Te elegimos negro para no tener esta conversacion...",
	"¿Oye tu hiciste el amor con tu mujer antes de casarte?  - No yo no. ¿Y tu?  -Yo sí, pero no sabía que se casaría contigo.",
	"—Mi Capitán, nos acercamos peligrosamente a un gran bloque de hielo.  —¿Iceberg?  — Sí, sí, sí, claro mi Capitán ¡Es enorme!",
	"―En ocasiones veo muertos. ―Después de 10 años trabajando en la funeraria, no te cansas de hacer la misma gracia, Paco?",
	"Me gusta la forma en la que mi perro se lame sus testículos. Me encantaría poder hacer lo mismo. Pero me gruñe y no me deja.",
	"+Doctor, por las noches sueño con unicornios jugando a futbol - Deberia dejar las drogas + No puedo! esta noche es la final!",
	"—Me han ofrecido tener realciones con una gorila por 500 € +Habrás dicho que no —He dicho que necesito 3 dias para reunir el dinero",
	"-Doctor, qué dice que tiene mi marido?  -Otitis Testicular.  -Y eso qué es?  -Que oye lo que le sale de los cojones..",
	"—Camarero, pon una de calamares a la rumana. —Perdone, señor, será a la romana. —Natasha, cariño, dile al gilipollas éste de dónde eres.",
	"Quina és la causa de la pederàstia? Nens sexys",
	"S'obre el teló i es veuen dos avis ballant. Com es diu la parada de metro? Ball carca (Vallcarca)",
	"—Papi, ¿qué es un cunnilingus?  —Sabes que una semilla se riega y crece una planta, ¿verdad?  —Sí.  —Pues un cunnilingus es comerte un coño.",
	"-Eres un egocéntrico - yo? pues anda que yo...!",
	"-Siempre quieres tener la ultima palabra.  -¡Eso es mentira!  -Bueno, pues perdona.  -Zapato.",
	"— GILIPOLLAS NO ENTRES! NO ENTRES EN LA IGLESIA! NOOOOO!  — Cari, qué peli estás viendo?  — Nada, el vídeo de nuestra boda.",
	"Era un tío tan feo tan feo, que a su muñeca hinchable siempre le dolía la cabeza",
	"-Perdí los resultados y no sé si su mujer tiene Sida o Alzheimer - ¿ Y qué hago doctor?  - Déjela en un bosque. Si regresa, no se la folle.",
	"-Saps com és la casa d'Stevie Wonder? +No. -Doncs ell tampoc!",
	"-“Sóc cirurgià plàstic” em va dir allargant-me la mà.  -Coi, sí que treballa de pressa.",
	"Que fa una vaca amb els ulls tancats? llet condensada",
	"Todo el material de ETA está hecho con modelos 'patentados'",
	"-¡Paco, cuánto tiempo! ¿Al final ganaste el concurso ese de aguantar mirando al sol? -Ya ves. -Genial tío. Bueno, dame un cupón.",
	"-Me voy de gira con un circo.  -¿Que sabes hacer?  -Trapecio.  -Yo también te quiero, cuidate.",
	"Què és pitjor que trobar-se un cuc a una poma? L'Holocaust",
	"Va un andalús i surt del bar",
	"Què és vermell i fa la mateixa olor que la pintura blava? La pintura vermella",
	"Què és verd i té rodes? - La gespa, lo de les rodes era broma.",
	"Un cavall entra a un bar. Diversa gent s'aixeca i marxa del bar, com a reacció al possible perill potencial de la situació",
	"The Game",
	"Què diu un jardiner quan perd el tractor? On és el meu tractor?",
	"-Pregunta'm si sóc un arbre. -Ets un arbre? -No",
	"-La tele cuesta 2395€. -¡Uy que cara! -Si la quiere más barata vaya a otra tienda...  -No, si hablo de lo feo que es usted!",
	"El colmo de un parado: llamarse Curro y tocar el contrabajo",
	"Un home entra en un restaurant turc -Teniu res de menjar?  -Kebab.  -Ah, llavors me'n vaig",
	"Porque los moros no tienen selección de natacion? Porque todos los que saben nadar estan en España",
	"— Te quiero — Manolo! Follando no vale!",
	"— Alto, policía. — Gordo, fontanero",
	"2 espermatozoides: -Tío, ¿tú ves algún óvulo por alguna parte? -Ni idea tío, pero estas trompas de falopio huelen a mierda que te cagas!!",
	"— Cariño... ¿me engañas con otra? —Vale.",
	"— Sólo me quieres por mis tetas. —¡No metas al perro en esto!",
	"En la consulta del médico: -Señor, lo siento, tendrá que dejar de masturbarse...  -¿Por qué?  -Porque sino la radiografia sale movida",
	"— Si tienes 5 porros y alguien te pide 2, ¿cuántos te quedan?  —5.  —Muy bien hijo. Si alguien quiere droga que se la pague.",
	"Odio cuando estoy leyendo una historia y no termina como yo unicornio",
	"—¿Capital de España? —La mayoría en Suiza.",
	"—La-bar-ba-coa, la barbacoa, como me gusta, ¡la barbecue!  —Paco por dios que están incinerando a mi madre.",
	"-Oiga, disculpe ¿es usted el abogado italiano?  +Si ¿en que puedo ayudarle?  --Expliqueme por qué es tan famosa la 'ley di gaga'",
	"-Que tal te fue el examen de francés?  -Tres bien.  -Ah, entonces genial, no?  -No, no, que sólo tuve tres bien.",
	"Papá, en mi cuarto hace mucho frío! - Ponte en la esquina. -¿Por? - Porque tiene 90 grados ",
	"- Papá tengo la sensación de que siempre me estan mirando...  + hijo mio, es que vives en cuenca.",
	"tu crees en el infierno... ? Si. en el infierno, el ferano, la primafera y el otoño.",
	"- ¿qué tal? cuanto tiempo hace que no te veo, ¿que es de tu vida?  - pues empiezo dentro de poco a trabajar en una academia de inglés - ah, ¿trabajo estable?  - no, table es mesa, trabajo es job",
	"- Usted se ha drogado?  - No señor minotauro",
	"Com es diu 'no estic d'acord' en africà?  M'opongo, m'opongo.",
	"En cuarto milenio: Si a la palabra 'Extrovertido' le cambiamos la E por la M, la X por la A y algunas letras más, nos sale la palabra 'Maricón' ¿Casualidad?",
	"- ¿Idiomas?  - Inglés - ¿Nivel?  - Level",
	"- ¿Y dice que habla muchos idiomas?  + Pues sí.  - Dígame tres...  + Three.  - ¿Y son…?  + Hijo.  - ¡Le estoy hablando en español!  + ¡Lo se, lo se, también lo hablo!  ",
	"-Qué significa 'anything' en inglés?  -Nada -Hombre, algo significará... no?",
	"Com es diu divorciada en rus? Vagina seminova",
	"Com es diu estovalles en africà? Uleeeeee!",
	"- su nivel de francés?  - hasta la campanilla - muy bien, puede usted empezar mañana",
	"- Hola, cómo te llamas?  - Kevin Costner, y tú?  — Manolo Saque de Banda.",
	"—¿Cómo ha ido tu operación de oído?  —Si.",
	"Qué cabrón mi vecino ¿Pues no se pone a llamar a mi puerta como un loco a las 4 de la mañana? Casi se me cae el taladro del susto.",
	"Una tía en la cola de un supermercado está poniendo todo de artículos individuales en la cinta de la caja (un donut, una pizza, un yogur, una manzana y un cepillo de dientes) cuando el cajero le pregunta: -¿Ud. es soltera, verdad? Y la tía le responde: -Pues sí, lo dice porque solo compro cosas para mí, ¿no? Y el chico le dice: -... No, lo decía por lo fea que eres, hija de puta",
	"- papa estoy embarazada - quee? como?  - trankilo no es tuyo - ah joder que susto",
	"- L'altre dia vaig anar a un curs de Crítica constructiva. - Ah si? I que tal?  - Una puta merda.",
	"La conocí en un ascensor. Soy el amor de subida",
	"—Termina ya que me voy a correr —¡Lo hago lo mas rápido que puedo!  —¡MAS RÁPIDO!  —¡JODER TOMA! Es la última vez que te plancho el chándal",
	"-Porqué Irene Villa no hace Harlem Shakes?  -Porque está con los terroristas.",
	"Como llaman a los bomberos en China' Pues, por telefono...",
	"—Te amo, hoy y siempre, me encantaría que fueras el padre de mis hijos.  — Soy el padre de tus hijos.  — Sobre ese tema, verás, te vas a reir...",
	"-¡Señor, nos atacan los alienígenas y su única debilidad es el análisis sintáctico y morfológico de las oraciones!  + ¡Y DECÍAN QUE ERA INÚTIL!",
	"- ¿Suspiráis, mi princesa?  - No, hoy me quedo",
	"Com es diu la Universitat Xinesa a Distància? WOK",
	"Un tío que se encuentra a una niña llorando al borde de un acantilado y le dice: - ¿Qué te pasa, nena?  + Pues que veníamos paseando mi padre mi madre y yo y mi madre se ha resbalado, se ha caído por el acantilado y mi padre al intentar rescatarla se ha caído también y ahora están los dos muertos!  Coge el tío, se baja la cremallera del pantalón y le dice: - ¡Vaya, hoy no es tu día de suerte!",
	"Esta un niño de 6 años en su habitación, y de repente se abre un vortex temporal y sale un hombre de 30 y le dice: - Hola, soy tu y vengo del futuro...  + walaaaa!!¿y que voy a ser de mayor?  Cierra el pestillo de la puerta, se baja la cremallera del pantalón y le dice: - Pederasta...",
	"Què compra un xino estèril? Espelmes.",
	"- No sé si conseguiré conquistar a esa chica... - ¿Tienes vacas y ovejas? - Sí. - Pues ya tienes mucho ganado.",
	"— ¿Cuales son tus aspiraciones en la vida? — Cocaina i pegamento",
	"– Joder, no sabes como odio a la gente competitiva...  – Sí, yo también.  – Jaja – Jajaja – Jajajaja – Jajajajaja – Jajajajajaja – Jajajajajajaja...",
	"Que guarda Darth Vader en el congelador...?  Helado Oscuro",
	"-Defínase en tres palabras: -Vago....",
	"Una feminista es una mujer que no tiene pelos en la lengua. Y si los tiene, son de una amiga.",
	"-Perdona, tenéis tabasco?  +Si, en la másquina",
	"-doctor doctor,oscúlteme +ráspido,en el armario!!!!",
	"Que es un palo? un boomerang que no vuelve ",
	"Que es un circuito? Un lugar donde hay elefantuitos, jirafuitas...",
	"—Mamá ¿has visto mi diario?  —No hija, tal vez lo dejaste en casa de tu mejor amiga, donde te acostaste con su novio el 27 de Mayo",
	"-Has estat mai dins un laberint?  -No.  -Doncs no saps el que et perds.",
	"—¿Cuales son los tres estados de la materia?  — Líquido, sólido y judío — HITLER, ¡FUERA DE CLASE! #LasAventurasDelPequeñoAdolf",
	"¿Qué dicen las azafatas de los aviones que van a Nueva York?: ¿A qué piso va?",
	"Entra un hombre en un bar y el camarero le pregunta: -Hola chaval, que va a ser?  -A pues yo ingeniero me estoy sacando los estudios -No no aver le pregunto que que quiere!  -A pues un bmw,una casita en el campo y que me toque la loteria -No no le pregunto que que va a tomar -Aaaah mmm nose, que hay? -Nada aqui limpiando la barra...",
	"-Señor Gutierrez, lo siento, tiene usted parkinson.  -Uy si, mire como tiemblo.",
	"Si un DJ se deja barba de dos dias, Pincha?",
	"—Ayer me follé a Rosa y a Margarita, soy el puto amo.  —Deja de tirarte flores.",
	"Ayer llamé a la guardia civil porque entraron en mi casa, y se llevaron hasta los vasos. -Y los detuvo? -Sisi y los de chupito también",
	"Le he dicho a mi mujer que el semen te vuelve invisible. -Y que tal? -Se lo ha tragado todo.",
	"De qué colegio eres? - Del sagrado corazón de cristo redentor y santa maria virgen immaculada concepción. -Ya. Entonces, de follar ni hablamos no?",
	"-Follamos? -¡No! Es que yo soy más de relaciones serias... -No te preocupes, sé hacerlo sin reirme",
	"¡Eso! Ahoguen a ese hijo de puta! -¡Cállate abuela! Que estamos en un bautizo...",
	"- Cariño, que haces tanto rato en el baño? - Cosas de mujeres. - ¿Estas fregándolo?",
	"-Wingardium Leviosa!  +Juan, aceptalo, tienes disfuncion erectil.",
	"-Estudias o trabajas?  -Soy español.  -Hostia perdona",
	"—Papá, ¿vendrás a mi graduación?  —No hijo. Ya me ensañarás las gafas cuando llegues a casa.",
	"Hija mía, sabes que soy muy tolerante y nunca te he reprochado tu estilo de vida, pero ¿podrías no escupirle al plátano antes de morderlo?",
	"—Oye cariño ¿A ti te parece guapa mi amiga Ana.  —¿La morena de labios carnosos, ojos verdes, grandes pechos y culazo?  —Sí.  —Ni me he fijado...",
	"+¿Nivel de inglés?  -Alto.  +¿Cómo se dice dos minutos en inglés?  -Chuminut.  +Bien, escriba una frase con two minuts.  -Te comería todo el chuminut. +Aprobado",
	"Quina és la consola preferida dels gitanos? La nintendo de ese",
	"- Juan! Quieres venir a mi fiesta de 18 años? - Vale tío, pero a los 3 meses me piro",
	"- ¡Mamá, mamá, en el disléxico me llaman colegio!",
	"—Vámonos de putas y echamos a suertes a ver quién paga. Si sale cara pago yo.  —Perfecto tío. Si es barata pago yo.",
	"-te llamas Juan?  +si -joder,entonces no tienes bicicleta??",
	"Oye, sabes cómo se llaman los habitantes de La Rioja?  Coño, pues todos no...",
	"¡Estoy a punto de cumplir un mes con mi novia! Sólo me falta un mes. Y una novia.",
	"Acabo de descubrir que mi pene erecto mide lo mismo que un paquete de arroz 'La Fallera'. Y nada, que acaban de echarme del Mercadona.",
	"— ¿Nivel de inglés?  — Alto — Traduzca 'Escoger un zapato'.  — Pick a shoe.  — Póngalo en una oración.  — Pick a shoe, usa impact trueno!.  — Contratado",
	"¡¡¿Como has podido follarte a mi hermana??!!  -Bueno, soy un hombre, estaba desnuda....¿Que querías que hiciera?  -¡¡ La autopsia hijo de puta!!.",
	"-Odio a la gente que hace como que te escucha pero no te hace ni puto caso.  -Las tres menos cuarto.",
	"- No se dice FOIÉ... se dice FUÁ!  - Ah sí? Pues ayer me FUÁ a tu hermana.",
	"Un hombre calvo está conversando con un amigo:- Sabes, me he comprado un champú anticaida- ¿Y te funciona?- No, me sigo resbalando en la ducha",
	"S'obre el teló i apareix un mono supergran. Nom de la ciutat? Monaco",
	"- Ayer tu novia me pidió que la ayudase a quitar una telaraña del techo y cuando me me subí a una silla me la chupó.  - TE LA QUÉ???  - Telaraña.",
	"- Mira, Eva, este es Adán, el único hombre sobre la tierra y al que amarás - ¿Y ese de ahí?  - Ah, ése es Jordi Hurtado. Estaba aquí cuando llegué.",
	"Cría cuervos y tendras más",
	"- Manolo, tienes una foto de tu mujer desnuda??  + No!  - Quieres una?",
	"- No sé contar. - Pues mira. Ya somos ocho.",
	"-¿Sabe usted inglés? -Si -¿Nivel? -Level",
	"No me funciona el modem de internet. -Que luces tiene encendidas? -La del salón y del pasillo",
	"Nivel de francés? -Hasta que me dan arcadas. -¡¡Contratada!!",
	"Tienes acento portugués. -Es que soy de Madeira. -Anda! Como pinocho!",
	"Per què es llepen el cul els lleons després de menjar? Per treure's el gust a negre",
	"-Cariño, que he venido pronto del trabajo, hoy me encargo yo de los niños, a ver, ¿cómo se llama este?",
	"-Eres bellísima. -Mentiroso, sólo quieres acostarte conmigo! -E inteligente.",
	"-Què fa un Amish al facebook? Enviar una sol·licitud d'amishtat.",
	"-¿De qué signo es tu mujer? - Debe ser de exclamación, porque se pasa el día gritándome...",
	"- ¿Me pone un zumo de piña?  - ¿Natural…?  - De Pontevedra, pero no creo que eso importe...",
	"- La aceptas como esposa en la salud, en la enfermedad, en la riqueza y en la pobreza hasta que la muerte os separe?  - Sí, no, si, no, no.",
	"Tengo tres llamadas perdidas de mi oftalmólogo. El de ver me llama.",
	"A nueve de cada diez hombres les gusta que las chicas vayan ligeritas de ropa. Al décimo le gustan los otros nueve.",
	"-Shhhhh. -Shhhhht. -Shhhhh. -Shhhhht. -Shhhhh. -Shhhhht. (Discusión entre una cobra y una bibliotecaria.)",
	"-¿Es grave Doctor?  -¿Ha oído ese refrán que dice que lo que no mata engorda?  -Sí.  -Pues ha debido comer alguna cosa que no engorda.",
	"-Hola, ¿es aquí el club de imbéciles?  -Sí, pero... ¿qué hace con todo ese estiércol?  -Vengo a abonarme.  -Dios santo, pase, será el líder.",
	"-Me siento solo.  -Yo también, sentarse es fácil.",
	"-No te das cuenta pero ¡TE TENGO EN EL BOTE!  -¡Deja de decir gilipolleces y REMA! ¡Subnormal!",
	"-Yo soy ateo.  - Yo anolo, ucho gusto.  - El gusto es ío.",
	"-¿Cómo se dice calzoncillos en noruego? Escondinavo",
	"- Perdone, ¿es este el ascensor de subida?  - No, he montado en otros mejores.",
	"Llaman a la puerta y es un técnico del ayuntamiento.  -Perdone, pero vamos a proceder al derribo del edificio contiguo.  -¿Conmiguo?",
	"-¿Te gustan más los Beatles o los Stones?  -A mí me gustan los Doors.  -Tienes que elegir uno.",
	"- Me tienes harta Manolo ...solo piensas en comer!!!  - A que te refieres croquetamente?",
	"-Doctor...estoy fatal, veo elefantes azules por todos los rincones...  -Ya ha visto usted a algun psiquiatra?  -No...de momento solo elefantes",
	"- Señor cuanto vale ese leggins - 24 euros!  - Y que marca?  - Los labios",
	"-¿Cómo se dice dame un beso en árabe? -Mohamed Lajeta",
	"¿Como te llamas?  — Maria De Los Ángeles ¿tu?  — Pedro de New York",
	"Doong! Dooong!  -mariano que hora es?  -la una.  -estàs seguro?  -como no lo voy a estar si lo he oido dos veces",
	"Despiden a dos empleados de Loctite porque se estaban pegando",
	"Hi havia un nen tant, tant orfe, que el va parir la seva tieta.",
	"-Quiero apuntarme al club Apple. -Nombre? -Maripad. -Hola Maripad. Soy Iphonso. -Encantada Iphonso. Dos besis.  -Imac, Imac.",
	"-Somos lo que comemos. -Jo tía, qué bien hablas, eres la polla.",
	"El hermano malvado de Plácido Domingo se llama Puto Lunes",
	"Per què fan gràcia 490 romans? - Perquè XD",
	"-Me pones un cafe bombón? -Como lo quieres, guapo!  -Bombón!  -Guapo!  -Coño con leche condensada!!!  -Hay que guarrete eres, guapo!",
	"Entra un a una llibreria. -Perdoni, té algun llibre per fer amics, calvo fill de puta?",
	"-Comemos algo? -Que?  -No sé, algo rápido. -Un leopardo?",
	"-Pizza Wiky, ¿dígame? -Quería una familiar. -¡Sus deseos son wikyórdenes! -¿Puede ser masa normal? -Me hacen decirlo así hijo de puta",
	"-Nunca me escuchas. -Ooooootra vez ha perdido el Betis.",
	"-Voy a ser el puto rey!!! -Paco!! -Dime plebeya -Coronaria... tienes una enfermedad coronaria -Que le corten la cabeza",
	"Dejad de llamarlas invitaciones de boda, son entradas",
	"-Papá -Dime hijo -¿Qué es dudar? -A ver, tu a quien quieres mas, ¿a papá o mamá? -A mamá -Pues que te lo explique ella, gilipollas",
];
